### ISSUE TITLE
workspace permission setting not applied

### ISSUE THREAD

**Issue by pbauer** [ploneintranet/ploneintranet#103]
Using the test-content I see that the "Participant policy" for both workspaces is set to "Consume". Workspace members should not be able to edit content in the workspaced but they can (using the user alice_lindstom).

**Comment by wengole** [comment]
@pbauer I've been looking at this. As far as I can see the integration of workspaces into the frontend has been done incorrectly. Some minor refactoring is in order which I should get done as part of the security checks task

**Comment by gyst** [comment]
Damn. This is still in the system and it's a release blocker for Mercury.
Will not ship with broken security.
@wengole I'd be extremely pleased if you could find the time to fix this.

**Comment by mattss** [comment]
@gyst FYI @wengole is on leave this week! I can't promise my own availability to get into this at the moment.

**Comment by gyst** [comment]
@mattss Thanks for the update, but bad news.
Relevant is also: https://workbamboo.com/#taskboard/4473/edit i.e. lack of test coverage on the security integration.

**Comment by mattss** [comment]
Following up on this, is there an example of what the UI should show when viewing a document I cannot edit? Unfortunately most of the prototype blurs the line between editing and viewing, so my default view of a rich page has the visual editor built into it.

**Comment by gyst** [comment]
Thinking about this I've come to realize that there should not be any document workflow within team spaces. It is my design intent that teamspaces are experienced as a single security zone, and security is only managed at the workspace level. That implies that objects within a space should all have a one-state workflow, and acquire view/edit/contributor settings from the workspace parent.

So what we need to do:
- apply one-state-workflow
- hide the workflow transition UI
- test that permissions are correctly acquired

In a later stage I will schedule stories for those parts of the system that do need document-level workflowing, like e.g. the news section. But in Mercury we can ship without.

Re viewing versus edit:

This one is editable
  http://demo.ploneintranet.net/minutes-of-2014-06-09

This one you can only view
  http://demo.ploneintranet.net/minutes-of-2014-05-03

**Comment by mattss** [comment]
@gyst your proposal certainly simplifies things for now. I am concerned about a workflow that makes documents immediately visible to others, as it leaves no room for getting content reviewed or proofed. A two state workflow at least lets me decide  when the document I am creating is in a finished enough state for others to see.

On another note - in the two examples you give, both have a header that allows the title, state to be edited and the content to be deleted, and both have a 'save' button. The only difference is that the body is not editable.

**Comment by gyst** [comment]
@mattss you're right that a one-state workflow would be invalid given the workspace design - the 'publish' transition is explicitly part of our security design.

There's multiple other issues with the security so I will schedule a story for that to be fixed in the Bristol sprint.
See https://www.assembla.com/spaces/ploneintranet/tickets/412
