### ISSUE TITLE
Fix the link to the attachment

### ISSUE THREAD

**Issue by ale-rt** [ploneintranet/ploneintranet#108]
We have a scale preview section in those two file:
- https://github.com/ploneintranet/ploneintranet/blob/687f32d4ebad3513c49c4d756c642668ae7cc45c/src/ploneintranet/activitystream/browser/prototype/comment.html#L37
- https://github.com/ploneintranet/ploneintranet/blob/687f32d4ebad3513c49c4d756c642668ae7cc45c/src/ploneintranet/activitystream/browser/prototype/post.html#L77
1. We should use a macro for this
2. the ancher href should be the attachment, non the preview

**Comment by pysailor** [comment]
For 2.) we need to fix the "StatusAttachments" BrowserView of microblog.browser. The `__call__` method, if no preview type like /thumb or /preview is appended to the URL, defaults to returning the attachment directly. But apparently still expecting an ATFile, not a dexterity file.
