### ISSUE TITLE
Provide an accurate fallback if preview generation fails

### ISSUE THREAD

**Issue by ale-rt** [ploneintranet/ploneintranet#122]
In some cases the preview cannot be generated (e.g. zip files, binary data, iso, crazy stuff...).

In this case I am returning as a fallback the site logo:
- https://github.com/ploneintranet/ploneintranet/blob/9dabfab0e4758cee5735485d8930b0734990f22b/src/ploneintranet/attachments/browser/upload.py#L22

We need a better fallback

**Comment by ale-rt** [comment]
@cornae I think this is something for you :)
I hope I have been clear, if not please contact me!

**Comment by cornae** [comment]
That's definitely not a good fallback :). You're right, we need a fallback for that. I will likely come up with something very similar to the 'preview being generated markup' that I gave to @reinhardt, but with a different class and text.

**Comment by jcbrand** [comment]
This issue was moved to ploneintranet/ploneintranet.prototype#2
