### ISSUE TITLE
'Private' workspace state not yet supported

### ISSUE THREAD

**Issue by mattss** [ploneintranet/ploneintranet#125]
In the original workspace implementation, there are three states of workspace 'visibility':
- Open
- Private
- Secret

Open workspaces are visible to all, and Secret ones are visible only to members.

However 'private' workspaces were designed as a more flexible solution where any user can _see_ the workspace and follow links to it, but they can only see 'public' content within it (and have no editing rights or 'social' functionality).

The above is fully implemented in the ploneintranet.workspace backend, but the prototype UI currently only really caters for you having full access to a workspace and all its content. As a result, non-workspace-members can currently view a 'private' workspace and interact with the social functions.

For more detail on the workspace policies, see the ploneintranet.workspace documentation (unfortunately lost in the merge - see #124):

https://github.com/ploneintranet/ploneintranet.workspace/blob/master/docs/policies.rst

**Comment by gyst** [comment]
There is no public content in private workspaces, that's the whole point.
Private workspaces should be listed in the "workspaces.html" view but not be linked nor be accessible for non-members.

In terms of implementation that means adjusting the workspaces.html listing to take this into account.

**Comment by mattss** [comment]
@gyst On the contrary, when we came up with the definition of private workspaces, we realised that some kind of 'public' content within them was required as teaser information, so that non-members can find out about the group and request access to it. We envisaged a non-member view of a private workspace that would include an introduction, and the 'join this workspace' action.

This is not represented in the prototype, and so may well need to be reconsidered for now, however that would leave very little difference between 'private' and 'secret' workspaces, and no place to request access to workspaces (which admittedly is not implemented either yet).

**Comment by gyst** [comment]
We fixed this in the Bristol sprint. Private workspaces are now not accessible to non-members. I agree that they should be able to self-invite and see an intro; however that can be implemented as an exception without requiring an actual security re-definition. Marking this ticket as done - we should open the "invite yourself to a private workspace" as a new feature at some point in the future.
