### ISSUE TITLE
stream file upload UTF8-safe

### ISSUE THREAD

**Issue by gyst** [ploneintranet/ploneintranet#127]
This follows up on #57.

If you upload bärtige_flößer.odt instead of basic.txt you get a hanging screen. I already removed one bug in 0d1db5c but apparently more needs to be done.

**Comment by ale-rt** [comment]
I cannot reproduce this anymore. Is it already fixed?

**Comment by gyst** [comment]
Yes I fixed that ages ago. Haven't maintained the issue tracker.

## 

   Guido Stevens  |  +31.43.3618933  |  http://cosent.nl

   s o c i a l   k n o w l e d g e   t e c h n o l o g y
