### ISSUE TITLE
All uninstall tests that test uninstall of resources, are broken. Well at least I found multiple of them

### ISSUE THREAD

**Issue by do3cc** [ploneintranet/ploneintranet#131]
The syntax to check for resources have changed, and we use this already for testing if resources get installed:
https://github.com/ploneintranet/ploneintranet/blob/251c8cf9f1e69c38030b6b6ac2f7c93c86ae1e60/src/ploneintranet/messaging/tests/test_setup.py#L40
The new syntax is not yet used in the uninstall profiles. There the assertion is true before and after uninstalling, for example:
https://github.com/ploneintranet/ploneintranet/blob/251c8cf9f1e69c38030b6b6ac2f7c93c86ae1e60/src/ploneintranet/messaging/tests/test_setup.py#L66

**Comment by pilz** [comment]
@pbauer As you recently merged uninstall support and our tests are green, is that fixed?

**Comment by pbauer** [comment]
Yes. The resources are now uninstalled from the registry and there is a test for that-
