### ISSUE TITLE
make fails at bower, 'chosen' tag of 0.9.11 not found.

### ISSUE THREAD

**Issue by adrianwhite** [ploneintranet/ploneintranet#132]
When running make (or bower install) @gyst and I both get:

```
bower chosen#0.9.11                    ENORESTARGET No tag found that was able to satisfy 0.9.11

Additional error details:
Available versions: 1.4.2, 1.4.1
make: *** [stamp-bower] Error 1
```

It is strange that only the two most recent versions are listed as on git you can still see the older version that is specified: https://github.com/harvesthq/chosen/releases/tag/v0.9.11
I've tried to get to the bottom of this this evening but could not get anywhere.
@jcbrand or @fulv are you able to take a look at this? @gyst needs it for demoing in Sorrento this week.

**Comment by jcbrand** [comment]
The _chosen_ devs created a bower specific repo and now older tags are not available anymore.

I created a ticket on their tracker but it was eventually rejected: https://github.com/harvesthq/chosen/issues/2294

I've already patched Patternslib and Mockup-core to make use of a workaround.

See for example here:
https://github.com/Patternslib/Patterns/commit/b59337ddf4eed1e3bd46cd8aae385c84b1a3b636
and here:
https://github.com/harvesthq/chosen/issues/2294

If after doing `make clean all` you still get the error, then it most likely means there is a bower dependency somewhere which depends on an older version of Patternslib which still has a dependency on "chosen#0.9.11" in its bower.json.

**Comment by gyst** [comment]
I've updated our toplevel bower.json but have made no headway in tracking down further "chosen#0.9.11" pins in our stack.

**Comment by macagua** [comment]
I have this update and I have the same error:

```
bower chosen#0.9.11                                       ENORESTARGET No tag found that was able to satisfy 0.9.11

Additional error details:
Available versions: 1.4.2, 1.4.1
make: *** [stamp-bower] Error 1
```

@jcbrand @gyst any idea to resolve this error?

**Comment by jcbrand** [comment]
@macagua  Should be fixed now. Just do a `git pull` and then `make clean all`.

**Comment by macagua** [comment]
@jcbrand thanks you! Now I have other error with jekyll #134
