### ISSUE TITLE
Installing _mr.developer. Installing instance. The constraint, 1.0, is not consistent with the requirement, 'plone.resourceeditor>=2.0.0.dev'. While:   Installing instance. Error: Bad constraint 1.0 plone.resourceeditor>=2.0.0.dev

### ISSUE THREAD

**Issue by zopyx** [ploneintranet/ploneintranet#133]
Current ploneintranet master checkout as of today does not work.

Installing _mr.developer.
Installing instance.
The constraint, 1.0, is not consistent with the requirement, 'plone.resourceeditor>=2.0.0.dev'.
While:
  Installing instance.
Error: Bad constraint 1.0 plone.resourceeditor>=2.0.0.dev

**Comment by pbauer** [comment]
I cannot reproduce that problem. Did you follow the instructions at http://docs.ploneintranet.org/installation/development.html?
