### ISSUE TITLE
Support about i18n

### ISSUE THREAD

**Issue by macagua** [ploneintranet/ploneintranet#135]
Hi Plonistas

There is some plan to add support for:
- i18n and translations.
- multilingual content support, with plone.app.multilingual package.

**Comment by macagua** [comment]
@gyst any comments about this question?

**Comment by gyst** [comment]
@macagua yes i18n has been raised by others as well. Is on our Venus roadmap now.
We have no plans for multilingual content.

**Comment by pilz** [comment]
translation support is quite good now and ongoing. You can translate for your language in transifex. As translations are an ongoing effort, I'd propose to close this ticket as we are doing i18n now.

**Comment by macagua** [comment]
@gyst thanks you :-) and @pilz now I am contributing with the Spanish translation ;)
