### ISSUE TITLE
dockerfile

### ISSUE THREAD

**Issue by svx** [ploneintranet/ploneintranet#137]
Hi,

is it ok if I issue a pr for the dockefile, even if I am not involved ? The dockerfile could be improved to follow best practices, be smaller and faster.
This will not change packages or the OS, but It would use 'chained commands', a optimized order for running  commands to improve speed, caching and so on ....

**Comment by jcbrand** [comment]
I think it's mainly @gyst using the docker file...

**Comment by ale-rt** [comment]
@svx your contribution is always welcome!
I am personally not using docker to develop plone intranet but any suggestion is really appreciated!

**Comment by gyst** [comment]
@svx sorry didn't see this. Yes contributions are welcome, and yes I'm the only consumer of the Dockerfile :-)

**Comment by acsr** [comment]
@gyst FYI (just in case you missed this):  Ramons stuff works like a charm...
motivates me to be the third docker file consumer...

> from: Ramon Navarro Bosch ramon.nb@gmail.com
> subject: [Plone-developers] Testing Plone 5 dev docker
> Date: 25. Juni 2015 17:35:19 MESZ
> to: plone-developers plone-developers@lists.sourceforge.net
> 
> I've been playing with docker latelly and I've created a "on the edge" plone 5 image that is the last green build of plone 5 on jenkins.plone.org.
> 
> You can use it with : 
> docker run --name plone -p 8080:8080 ramonnb/docker-base-plone:5.0
> 
> If you want to try plone 5 "on the edge" on a windows/mac os x just download https://kitematic.com/ and run the image ramonnb/docker-base-plone (you must choose the tag 5.0)
> 
> So you can have a onthe edge plone 5 running on any windows/mac desktop with a nice app that downloads and runs for you everything with only three "clicks" :P
> 
> R
