### ISSUE TITLE
Rewrite todo API

### ISSUE THREAD

**Issue by wengole** [ploneintranet/ploneintranet#14]
<a href="https://github.com/wengole"><img src="https://avatars.githubusercontent.com/u/383857?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wengole](https://github.com/wengole)**
_Tuesday Mar 10, 2015 at 15:45 GMT_
_Originally opened as https://github.com/ploneintranet/ploneintranet.todo/issues/3_

---

Currently this stores a massive mapping of userids to their unread content UIDs.

This is bad. After speaking with @mattss a much better solution was formulated:
- Upon creation of a "todo", add an todo to all selected users as annotation on the user
- Simultaneously add an "unread" userid to the content as an annotation 

These changes would be handled by the API from the same calls.

**Comment by gyst** [comment]
Putting this on hold. This is the "news" story polluting the "todo" story. Both stories are, separately, scoped for Venus.

**Comment by gyst** [comment]
Both the original implementation and this proposal are flawed. Cancelling this ticket, scheduling proper implementation in separate stories.
