### ISSUE TITLE
Retro: improve jenkins setup

### ISSUE THREAD

**Issue by jaroel** [ploneintranet/ploneintranet#170]

**Comment by mattss** [comment]
As part of the retro we agreed that the jenkins setup needed adjusting, as the number of jobs that run make it hard to keep track of what is going on.

We concluded that:
- Quicktests are more hassle than they are worth now we only have one repo
- Master should always be green
- We do not need to build all branches all the time as this adds noise during development
- Branches need to be green at the time of pull request (use github pull request plugin)

**Comment by mattss** [comment]
Ok I think that pull request integration is now working - just successfully did a full test here: https://github.com/ploneintranet/ploneintranet/pull/196

We now have three jenkins jobs:
1. Clean master (runs daily)
2. Master (runs on every master commit)
3. Pull request builder (tests every pull request)

/cc @gyst

**Comment by mattss** [comment]
I am also hoping to add a 'bot' account (ploneintranet-jenkins-bot) so that @do3cc doesn't get blamed for spamming everyone all the time(!) (Jenkins currently uses his API key to add comments to github issues).

**Comment by mattss** [comment]
Jenkins github integration is now managed by the dummy account @ploneintranet-jenkins, which should hopefully make the status messages clearer.
