### ISSUE TITLE
Retro: default pair programming setup

### ISSUE THREAD

**Issue by jaroel** [ploneintranet/ploneintranet#171]

**Comment by pbauer** [comment]
@wengole should demo his floobits-setup (http://floobits.com). 
Best practices:
- login to floobits.com (sign up with github)
- share the directory src/ploneintranet in a public workspace 
- use the audio-chat on floobit.com
- maybe close workspaces after a pair-programming-session to prevent your files being ediable?

**Comment by gyst** [comment]
@wengole would be helpful if you could write down your setup.
