### ISSUE TITLE
A comment on a status-update removes all previous comments

### ISSUE THREAD

**Issue by pbauer** [ploneintranet/ploneintranet#175]
All comments are visible again when reloading the page. The pat-inject-config probably injects into the whole comment-area, thereby removing any existing comment.

Also (maybe not related or a non-issue): In the prototype you can only comment once, subsequent comments have no effect.

**Comment by pysailor** [comment]
This is an old issue that Cornelis said is fine for the moment. In the long run, not all existing comments, but only the latest X ones will be displayed. Once we have that, we can also use that for the injection.
See also the Note under view/get_workflow_state
