### ISSUE TITLE
Replace publishTraverse / toggle views with proper POST requests

### ISSUE THREAD

**Issue by mattss** [ploneintranet/ploneintranet#214]
The /plonesite/@@toggle_like/1234 views in ploneintranet.network make for nice URLs, but will cause issues with CSRF.

These methods should just use arguments and enforce POST requests.

(Ref https://github.com/ploneintranet/ploneintranet/pull/204#issuecomment-103517983)

**Comment by mattss** [comment]
As @jaroel also pointed out, the pattern of /plonesite/@@toggle_like/1234 implies that this is a unique resource, rather than an action. Posting to /plonesite/@@toggle_like with a request parameter would be much clearer.

**Comment by gyst** [comment]
It is also a unique resource; apart of the action handler it is also the view that renders the form for that action. 

Fixed this so that rendering the form is a GET while performing the action is a POST.
