### ISSUE TITLE
Remove Travis integration, in favour of Jenkins

### ISSUE THREAD

**Issue by wengole** [ploneintranet/ploneintranet#22]
<a href="https://github.com/mattss"><img src="https://avatars.githubusercontent.com/u/1155400?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mattss](https://github.com/mattss)**
_Monday Mar 09, 2015 at 15:15 GMT_
_Originally opened as https://github.com/ploneintranet/ploneintranet.suite/issues/48_

---

I would like to suggest removing travis support for now, and focussing on the Jenkins integration. Maintaining two completely different CI setups is time consuming and difficult. Currently the travis builds are quite error-prone and therefore introduce a lot of noise in emails and IRC.

**Comment by wengole** [comment]
<a href="https://github.com/adamcheasley"><img src="https://avatars.githubusercontent.com/u/42489?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [adamcheasley](https://github.com/adamcheasley)**
_Monday Mar 09, 2015 at 15:17 GMT_

---

+1

**Comment by wengole** [comment]
<a href="https://github.com/wengole"><img src="https://avatars.githubusercontent.com/u/383857?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [wengole](https://github.com/wengole)**
_Monday Mar 09, 2015 at 15:18 GMT_

---

+1

**Comment by wengole** [comment]
<a href="https://github.com/mattss"><img src="https://avatars.githubusercontent.com/u/1155400?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mattss](https://github.com/mattss)**
_Wednesday Mar 11, 2015 at 09:41 GMT_

---

I would love to move this forward if possible. Are there any particular objections? /cc @gyst @do3cc

**Comment by do3cc** [comment]
No objections from my side.
Btw, here is our new jenkins config: https://github.com/ploneintranet/ploneintranet.jenkins

**Comment by gyst** [comment]
@wengole OK with me. Isn't this done already?

**Comment by mattss** [comment]
I had issues disabling the travis builds, but this is effectively done as a result of the code merge.
