### ISSUE TITLE
Update docs.ploneintranet.org build process

### ISSUE THREAD

**Issue by mattss** [ploneintranet/ploneintranet#225]
Since the updates in https://github.com/ploneintranet/ploneintranet/pull/223, the 'generate-docs' command has been removed from buildout.

@pysailor mentioned there was an automated process that rebuilt the docs hosted on ploneintranet.org regularly. This will need updated to use the new command `make docs`

/cc @pilz

**Comment by pilz** [comment]
I changed the cronjob. make docs spits out a million autoconv Import errors but runs through and I do see the site, so it seems good. @mattss?

**Comment by mattss** [comment]
Thanks there are a few teething issues going on that I'm resolving.

**Comment by mattss** [comment]
Ah yes just remembered - does the cron job also re-run buildout? If not you will need to run it once manually to get the code paths into sphinx

**Comment by pilz** [comment]
Hehe, no, hasn't been run for a long time. Done now, looks still good

**Comment by mattss** [comment]
This is working well now - thanks @pilz!
