### ISSUE TITLE
Superimpose updating social post text over top of text area

### ISSUE THREAD

**Issue by wengole** [ploneintranet/ploneintranet#23]
<a href="https://github.com/bfackland"><img src="https://avatars.githubusercontent.com/u/2538526?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bfackland](https://github.com/bfackland)**
_Friday Aug 08, 2014 at 08:15 GMT_
_Originally opened as https://github.com/ploneintranet/ploneintranet.theme/issues/14_

---

This will make out prototype a little more representative of the desired end result

**Comment by wengole** [comment]
<a href="https://github.com/ldexterldesign"><img src="https://avatars.githubusercontent.com/u/1715809?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ldexterldesign](https://github.com/ldexterldesign)**
_Wednesday Oct 08, 2014 at 11:26 GMT_

---

Hey @bfackland,

I'm closing this issue

If you feel it's still relevant by all means reopen it

Regards,

**Comment by wengole** [comment]
<a href="https://github.com/gyst"><img src="https://avatars.githubusercontent.com/u/122351?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gyst](https://github.com/gyst)**
_Wednesday Oct 08, 2014 at 15:01 GMT_

---

IIRC the current implementation is only partially feature complete and may require significant refactoring in order to support shortcode triggers.

**Comment by jcbrand** [comment]
This issue was moved to ploneintranet/ploneintranet.prototype#22
