### ISSUE TITLE
Should we move away from buildout.plonetest?

### ISSUE THREAD

**Issue by giacomos** [ploneintranet/ploneintranet#239]
It seems that buildout.plonetest is too much a moving target for our needs, today I had to pin the git revision because the cfg file that we were using was upgraded from Plone 5.0a3 to 5.0b2

Temporarily I fixed that issue with this:
https://github.com/ploneintranet/ploneintranet/commit/0f1126fac12570c7d0e3c379f8b7b7ba190f9f42

Nevertheless I think that the gain of being linked to that buildout is not worth enough. We could just pick the few lines that are there and take our way.

**Comment by gyst** [comment]
+1 will work that into the 5.0b2 upgrade

**Comment by gyst** [comment]
Fixed
