### ISSUE TITLE
Firefox compatibility

### ISSUE THREAD

**Issue by wengole** [ploneintranet/ploneintranet#25]
<a href="https://github.com/gyst"><img src="https://avatars.githubusercontent.com/u/122351?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gyst](https://github.com/gyst)**
_Friday Feb 27, 2015 at 20:02 GMT_
_Originally opened as https://github.com/ploneintranet/ploneintranet.theme/issues/99_

---

None

**Comment by jcbrand** [comment]
This issue was moved to ploneintranet/ploneintranet.prototype#21
