### ISSUE TITLE
visual finishing

### ISSUE THREAD

**Issue by zopyx** [ploneintranet/ploneintranet#250]
See screenshot:
- no focus on the title field
- no visual padding between the two input fields
- what is "\e" ?
- spinning wheel forever (other screenshot)

![screenshot 2015-06-01 17 22 25](https://cloud.githubusercontent.com/assets/594239/7916286/2f2fb452-0883-11e5-8fe4-22cd56936b1a.png)

![screenshot 2015-06-01 17 26 14](https://cloud.githubusercontent.com/assets/594239/7916310/5afca892-0883-11e5-8cc7-cca376e1c64a.png)

**Comment by gyst** [comment]
Confirmed. The hamburger menu is not implemented as specified in the prototype. The add workspace modal does not match the design prototype.

**Comment by pilz** [comment]
Hamburger is fixed and the modal is different now with whitespace
