### ISSUE TITLE
group by tag plone.protect error

### ISSUE THREAD

**Issue by gyst** [ploneintranet/ploneintranet#255]
@pilz The "group by tag" function doesn't work anymore. It triggers
WARNING plone.protect error parsing dom, failure to add csrf token to response for url http://localhost:8080/Plone/workspaces/open-market-committee/@@sidebar.default

This is NOT a result of merging Cillian's design cleanup - verified that locally by doing a merge revert, no effect.

**Comment by cillianderoiste** [comment]
@gyst I can't reproduce this on master and I do see the hidden input field for _authenticator. I also tested against a robot-server instance. The warning sounds like plone.protect has trouble with the markup produced by @@sidebar.default. I'll clean it up and see if there are any validation errors which could be causing problems (perhaps we have different versions of libxml or something like that).

**Comment by cillianderoiste** [comment]
@gyst could you see if e74f84b0 improves things?
