### ISSUE TITLE
Workspace sidebar: entering a folder doesn't update the breadcrumbs

### ISSUE THREAD

**Issue by cillianderoiste** [ploneintranet/ploneintranet#258]
This is because we inject the @@sidebar.default tile when navigating to a folder. Ideally we would be able to also inject the breadcrumbs from another tile (but this isn't yet supported in patterns: Patternslib/Patterns#406) so we will need to use a view which includes both the sidebar tile and the breadcrumbs.

**Comment by pilz** [comment]
@cillianderoiste I am loading the folder view instead of only the sidebar now. That includes the breadcrumbs and so I can multi-inject it.
