### ISSUE TITLE
Broken pre-commit hook

### ISSUE THREAD

**Issue by fulv** [ploneintranet/ploneintranet#278]
When I attempted a commit earlier I got this error:

```
.git/hooks/pre-commit: line 2: bin/code-analysis: No such file or directory
```

For the record, this is all I have in the pre-commit:

```
> cat .git/hooks/pre-commit
#!/bin/bash
bin/code-analysis
```

Sure enough, there is no `code-analysis` anywhere.

**Comment by mattss** [comment]
code-analysis is built by plone.recipe.codeanalysis in base.cfg here: https://github.com/ploneintranet/ploneintranet/blob/master/base.cfg#L83

I've just cleared my local 'bin' dir and re-run buildout on master, and the code-analysis script is built correctly. Possibly your buildout encountered a problem and did not complete?
