### ISSUE TITLE
Example in documentation should not use TAL

### ISSUE THREAD

**Issue by wengole** [ploneintranet/ploneintranet#28]
<a href="https://github.com/fulv"><img src="https://avatars.githubusercontent.com/u/460742?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [fulv](https://github.com/fulv)**
_Friday Feb 27, 2015 at 22:42 GMT_
_Originally opened as https://github.com/ploneintranet/ploneintranet.theme/issues/102_

---

None

**Comment by wengole** [comment]
<a href="https://github.com/fulv"><img src="https://avatars.githubusercontent.com/u/460742?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [fulv](https://github.com/fulv)**
_Friday Feb 27, 2015 at 22:45 GMT_

---

ploneintranet/pat-checklist-picker#1
Connects #96

**Comment by wengole** [comment]
<a href="https://github.com/fulv"><img src="https://avatars.githubusercontent.com/u/460742?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [fulv](https://github.com/fulv)**
_Friday Feb 27, 2015 at 22:53 GMT_

---

Connects #96

**Comment by jcbrand** [comment]
This issue was moved to ploneintranet/ploneintranet.prototype#18
