### ISSUE TITLE
Performance Degradation for non-admins

### ISSUE THREAD

**Issue by pilz** [ploneintranet/ploneintranet#289]
As allan_neece entering a folder in a workspace takes a long time depending on the number of workspaces in the system.
It is quick for the admin user.

We tracked it down to the WorkspaceLocalRoleAdapter
https://github.com/ploneintranet/ploneintranet/blob/master/src/ploneintranet/workspace/configure.zcml#L71-L73

Comment it out and folder loading for allan is quick again.

I don't immediately understand what the issue was that was solved here. @adamcheasley can you shed some light?
https://github.com/ploneintranet/ploneintranet/commit/b5edac6a42a05e0c096921135d08cc587d8903f1

**Comment by pilz** [comment]
@mattss @pysailor That's how far I came

**Comment by mattss** [comment]
Aha! This adapter is documented here:

http://docs.ploneintranet.org/development/components/workspace.html#implementation-notes

Basically it will elevate 'Owner' to 'Reviewer' if the 'Publishers' policy is set on the workspace. This allows users to publish their own content, but not the content of others in this particular policy.

I will try and investigate why this adapter is being very slow.
