### ISSUE TITLE
Editor plugin for contentbrowser

### ISSUE THREAD

**Issue by wengole** [ploneintranet/ploneintranet#29]
<a href="https://github.com/fulv"><img src="https://avatars.githubusercontent.com/u/460742?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [fulv](https://github.com/fulv)**
_Wednesday Mar 04, 2015 at 16:04 GMT_
_Originally opened as https://github.com/ploneintranet/ploneintranet.theme/issues/109_

---

None

**Comment by wengole** [comment]
<a href="https://github.com/jcbrand"><img src="https://avatars.githubusercontent.com/u/683911?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcbrand](https://github.com/jcbrand)**
_Wednesday Mar 04, 2015 at 16:10 GMT_

---

@fulv do you know whether there is an existing contentbrowser somewhere I can take a look at?

**Comment by wengole** [comment]
<a href="https://github.com/fulv"><img src="https://avatars.githubusercontent.com/u/460742?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [fulv](https://github.com/fulv)**
_Wednesday Mar 04, 2015 at 16:17 GMT_

---

@jcbrand You could look at Plone's contentbrowser for TinyMCE.

**Comment by wengole** [comment]
<a href="https://github.com/fulv"><img src="https://avatars.githubusercontent.com/u/460742?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [fulv](https://github.com/fulv)**
_Wednesday Mar 04, 2015 at 16:19 GMT_

---

https://github.com/plone/Products.TinyMCE/tree/master/Products/TinyMCE/skins/tinymce/plugins/plonebrowser

**Comment by wengole** [comment]
<a href="https://github.com/jcbrand"><img src="https://avatars.githubusercontent.com/u/683911?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcbrand](https://github.com/jcbrand)**
_Wednesday Mar 04, 2015 at 16:46 GMT_

---

@fulv thanks, will do

**Comment by jcbrand** [comment]
This issue was moved to ploneintranet/ploneintranet.prototype#17
