### ISSUE TITLE
Should a user be able to filter and/or add new tags?

### ISSUE THREAD

**Issue by wengole** [ploneintranet/ploneintranet#30]
<a href="https://github.com/adrianwhite"><img src="https://avatars.githubusercontent.com/u/1485452?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [adrianwhite](https://github.com/adrianwhite)**
_Monday Mar 09, 2015 at 09:44 GMT_
_Originally opened as https://github.com/ploneintranet/ploneintranet.theme/issues/112_

---

Currently you can only select existing tags from a potentially huge list:
![screen shot 2015-03-09 at 09 42 16](https://cloud.githubusercontent.com/assets/1485452/6552699/b4179e3a-c640-11e4-9d9f-2ea7196885b5.png)

**Comment by cornae** [comment]
Well, since @pysailor nicely designed and developed it now, yes ;). But it should be retro fitted as such into the prototype.

**Comment by jcbrand** [comment]
This issue was moved to ploneintranet/ploneintranet.prototype#16
