### ISSUE TITLE
Solr robot tests

### ISSUE THREAD

**Issue by mattss** [ploneintranet/ploneintranet#303]
(from https://github.com/ploneintranet/ploneintranet/pull/299#issuecomment-114071198)

@gyst wrote:

> The test coverage is quite limited. I would expect some integration/functional tests in the search/solr package that verify a full solr roundtrip at the python level. Additionally the robot tests in the suite should exercise solr and check solr-specific features, like the ngram substring matching I just activated and the spelling suggestions.

**Comment by mattss** [comment]
Suggestion was to add these robot tests into ploneintranet.search.solr, rather than polluting the main acceptance tests from the suite with all the solr setup and teardown stuff.

**Comment by gyst** [comment]
#549 highlights the need for solr robot tests. We need to detect solr search regressions as part of automated QA.

**Comment by gyst** [comment]
fixed in #628
