### ISSUE TITLE
Is it PloneIntranet, plone.intranet, ploneintranet or Plone Intranet?

### ISSUE THREAD

**Issue by wengole** [ploneintranet/ploneintranet#32]
<a href="https://github.com/cillianderoiste"><img src="https://avatars.githubusercontent.com/u/643494?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cillianderoiste](https://github.com/cillianderoiste)**
_Monday Mar 09, 2015 at 11:01 GMT_
_Originally opened as https://github.com/ploneintranet/ploneintranet.docs/issues/10_

---

All variants are currently used in the docs.

**Comment by wengole** [comment]
<a href="https://github.com/jcbrand"><img src="https://avatars.githubusercontent.com/u/683911?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcbrand](https://github.com/jcbrand)**
_Monday Mar 09, 2015 at 12:55 GMT_

---

Depends on the context. I think PloneIntranet and plone.intranet should never be used. "ploneintranet" makes sense in the context of package names. Otherwise "Plone Intranet".

**Comment by wengole** [comment]
<a href="https://github.com/adamcheasley"><img src="https://avatars.githubusercontent.com/u/42489?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [adamcheasley](https://github.com/adamcheasley)**
_Monday Mar 09, 2015 at 12:57 GMT_

---

Agreed. I would use "Plone Intranet" where ever possible.

**Comment by wengole** [comment]
<a href="https://github.com/jcbrand"><img src="https://avatars.githubusercontent.com/u/683911?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcbrand](https://github.com/jcbrand)**
_Monday Mar 09, 2015 at 12:58 GMT_

---

It's unfortunate that the IRC channel is #plone.intranet (and not #ploneintranet), I guess that introduces some confusion.

**Comment by wengole** [comment]
<a href="https://github.com/adrianwhite"><img src="https://avatars.githubusercontent.com/u/1485452?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [adrianwhite](https://github.com/adrianwhite)**
_Monday Mar 09, 2015 at 13:09 GMT_

---

blame @mattss for the IRC channel name

**Comment by wengole** [comment]
<a href="https://github.com/cillianderoiste"><img src="https://avatars.githubusercontent.com/u/643494?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cillianderoiste](https://github.com/cillianderoiste)**
_Monday Mar 09, 2015 at 13:39 GMT_

---

Should we change the IRC channel? I'll fix up the docs.

**Comment by wengole** [comment]
<a href="https://github.com/jcbrand"><img src="https://avatars.githubusercontent.com/u/683911?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcbrand](https://github.com/jcbrand)**
_Monday Mar 09, 2015 at 13:46 GMT_

---

+1 for changing channel name, but we'll need to have everyone informed.

**Comment by gyst** [comment]
+1 for "ploneintranet" && "Plone Intranet" && irc "#ploneintranet"

**Comment by wengole** [comment]
@jcbrand @gyst @mattss @cillianderoiste I can put a topic (in all caps) in the old/current channel, if/when we move to #ploneintranet
