### ISSUE TITLE
POSKeyError when using ZEO

### ISSUE THREAD

**Issue by gyst** [ploneintranet/ploneintranet#324]
Running the suite testcontent setup triggers a POSKeyError in a ZEO setup.

Reproduce:
- bin/buildout -c zeo.cfg
- bin/zeo start
- bin/instance fg
- add Plone Site
- portal_setup import "suite create testing content" all steps

This does not happen when just running suite:default. It may be an indication though of a deeper issue in our stack - for example in the document conversion @wengole is currently refactoring.

I was testing ZEO as part of themeswitching but have validated that none of the themeswitching related hackery has anything to do with it (by rewinding master to b9be0d47a0 and rewinding CMFPlone and p.a.theming to unchanged origin/master).

The error consistently happens right after the rolemap is imported. No time to dig deeper now, filing in case somebody wants/needs to pick up on this.

2015-06-27 11:50:59 WARNING ploneintranet.docconv.client.fetcher fetchPreviews failed: 'NoneType' object has no attribute 'contentType'
2015-06-27 11:51:16 INFO GenericSetup.rolemap Role / permission map imported.
2015-06-27 11:51:17 ERROR Zope.SiteErrorLog 1435405877.920.526107621937 http://localhost:8080/Plone/portal_setup/manage_importAllSteps
Traceback (innermost last):
  Module ZPublisher.Publish, line 146, in publish
  Module Zope2.App.startup, line 301, in commit
  Module transaction._manager, line 89, in commit
  Module transaction._transaction, line 329, in commit
  Module transaction._transaction, line 446, in _commitResources
  Module ZODB.Connection, line 781, in tpc_vote
  Module ZEO.ClientStorage, line 1098, in tpc_vote
  Module ZEO.ClientStorage, line 929, in _check_serials
POSKeyError: 0x075a25

**Comment by gyst** [comment]
Update: this may well be a duplicate of #251 . If that is true, this ZEO adds a fully reliable reproduction of that issue because it happens every time in a ZEO setup.

**Comment by gyst** [comment]
Duplicates #251. Cannot reproduce anymore. Closing.

**Comment by ale-rt** [comment]
I have just been bitten by this one:

```
2015-09-01 17:10:01 ERROR Zope.SiteErrorLog 1441120201.860.486337279172 http://localhost:9001/Plone/portal_setup/manage_importAllSteps
Traceback (innermost last):
  Module ZPublisher.Publish, line 146, in publish
  Module Zope2.App.startup, line 301, in commit
  Module transaction._manager, line 89, in commit
  Module transaction._transaction, line 329, in commit
  Module transaction._transaction, line 446, in _commitResources
  Module ZODB.Connection, line 781, in tpc_vote
  Module ZEO.ClientStorage, line 1098, in tpc_vote
  Module ZEO.ClientStorage, line 929, in _check_serials
POSKeyError: 0x2e2e
```

Fresh (although customized) buildout with zeo+solr.

After a CTRL+R the import procedure completed succesfully.

**Comment by gyst** [comment]
Reopening.

**Comment by pilz** [comment]
hasn't happen again to my knowledge in two years. Closing
