### ISSUE TITLE
Enable Imagepicker in pat-raptor

### ISSUE THREAD

**Issue by pilz** [ploneintranet/ploneintranet#334]
The raptor editor needs support to add images. 
Instead of a site browser to pick images, we could offer a modal with a search field to search for images that the current user can see. Results are added to the modal as thumbs and can be selected and inserted.

Also take #83 into consideration.

**Comment by jcbrand** [comment]
We can't use anything from Star, because it uses a different editor (redactor).

**Comment by pilz** [comment]
F...! Which options do we have? I bet raptor also has some sort of picker and we need to couple it to a backend. Anything reusable there?

**Comment by jcbrand** [comment]
What do we need? Do we absolutely need them to be able to pick already uploaded images?

This might help: https://www.raptor-editor.com/documentation/tutorials/file-manager

The `uriPublic` option sounds like it might mean a location where already uploaded files can be picked, but I'm not sure, the description is very vague.

I'll have to investigate tomorrow.

**Comment by gyst** [comment]
Initial implementation in #391

**Comment by pilz** [comment]
So no imagepicker in PI?

**Comment by gyst** [comment]
I thought we have a different editor now, with a different image picker????

**Comment by pilz** [comment]
An editor is always an epic. And while I would love to have ProseMirror in, it requires too much extra to include. Like design by cornelis. It can't do tables yet. So we still have raptor, soon with an image picker developed by Rok.

**Comment by gyst** [comment]
OK, assigning to Rok then. Would be cool to have this in Venus but not a release blocker.

**Comment by bfackland** [comment]
+1

**Comment by pilz** [comment]
This has been done already. Waiting just for a green jenkins to make the pr

**Comment by bfackland** [comment]
Awesome :)

> On 22 Oct 2015, at 17:35, Alexander Pilz notifications@github.com wrote:
> 
> This has been done already. Waiting just for a green jenkins to make the pr
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Ben Ackland, Projects Director
Netsight Internet Solutions Limited
Tel: +44 (0)117 90 90 90 1

Registered in England no. 3892180
Registered office: 40 Berkeley Square, Bristol, BS8 1HU, United Kingdom

**Comment by pilz** [comment]
raptor has been replaced by redactor which has an image picker
