### ISSUE TITLE
Object events should go into the activity stream

### ISSUE THREAD

**Issue by pilz** [ploneintranet/ploneintranet#335]
According to @cornae, certain object events should appear in the activity stream. 
Example:
- User has added Task to Workspace
- User has published document in Workspace

**Comment by bfackland** [comment]
@gyst wrote: "means firing a microblog update on publication, not before".

**Comment by bfackland** [comment]
@pilz Ben C will take a look at this today.

**Comment by mattss** [comment]
As far as we can tell, there is no way to reference other content from a status update (other than attaching files directly to the status update, which is not what we want).

There doesn't seem to be anything in ploneintranet.microblog to support this kind of thing, which makes this seem like an awfully big architectural change to try and introduce at this stage (especially without @gyst around today).

**Comment by pilz** [comment]
Wow, ok. I though that we had the option to add simple "notes" style updates there. If that requires a backend update, skip that for now

**Comment by mattss** [comment]
@wengole is going to get some events implemented to start this off, but without a way to link from status updates to other content, the messages are not going to be very useful.

**Comment by mattss** [comment]
@pilz That may be possible - but without input from @gyst I'm not sure!

**Comment by bfackland** [comment]
For now I guess we could include relative resolve_uid URLs in the posts? That won't go bad. In future a migration to some better reference storage.

**Comment by mattss** [comment]
An offline conversation resulted in this issue being abandoned. @gyst can you confirm that this issue should be closed, in favour of a different implementation?

**Comment by wengole** [comment]
Working code here https://github.com/ploneintranet/ploneintranet/compare/publish-events

**Comment by gyst** [comment]
Yes I'm awfully sorry for the confusion I co-caused here and the work @wengole did for nothing. I initially responded literally while walking into a meeting. I've broken this into two separate tickets now:
- #359 Sharing an existing file into the stream
- #360 Show "published" events in notifications
