### ISSUE TITLE
Library Page: Need to show attached image

### ISSUE THREAD

**Issue by pilz** [ploneintranet/ploneintranet#352]
Currently when you add a news item, you can attach an image. However it doesn't show in the PI view of the item

**Comment by gyst** [comment]
That's intentional. Cornelis wants people to use the wysiwig editor to place images inline. The leadimage on all content types on the other hand are used in the list views of those items, so if you go to the parent folder you'll see it there.

**Comment by pilz** [comment]
Actually Cornelis got some additional ideas :) I implemented an in between good enough state which allows us to get some colour in in #373. Then we can even add the checkboxes, Cornelis suggests for further tuning later.

**Comment by gyst** [comment]
The whole checkboxes idea comes from the news cms and should be implemented when we also replace Barceloneta with a PI-native library cms based on news cms.

Fixed in #373 closing this ticket.
