### ISSUE TITLE
Show "published" events in notifications

### ISSUE THREAD

**Issue by gyst** [ploneintranet/ploneintranet#360]
As a user,
When I access the system
I want to be able to see a list of notifications about activity other users did
like publishing or modifying content,
So I can easily get an overview of what changed since I last logged in.

We want to not pollute the main activity stream with publication events, since this is a system event and it would easily swamp the stream with boring bulk uploads.

At the same time, showing these events can be useful. That's what the notification system has been designed for. Currently ploneintranet.notifications is an abandoned ghost town with an unknown backend status and an incomplete frontend that has security issues and is likely also not completely prototype-compatible.

Todo:
- Clean up the frontend. This uses a viewlet, which is OK because it's a sitewide facility that should render on all pages across all apps.
- Subscribe to workflow transition events and turn them into notifications. Who is subscribed to these notifications? -> any member of a workspace in which a publication event takes place. Nothing outside workspaces for now.
- Ideally, use an async worker to actually explode a single synchronous zope event into potentially hundreds or thousands of per-user notifications.
- Viewing the notification box should be smart. It should detect bulk actions by the same user by not showing 35 separate notifications but by showing a single notification message: "User X published 35 files". Simple algorithm: author=None; _type=None; batch=[]; for notification in storage: if (notification.user==author or author is None) and (notification.event_type == _type or _type is None): batch.append(notification); ... and then in the end render(batch).

The last (batching) feature is less urgent and may be extracted into a separate follow-up ticket.

Note that this is related to #359 but a completely different story and implementation. If you're publishing a file, #359 enables you to manually share that to the main stream. In this ticket, as a user I can selectively see what other users have been doing.

**Comment by gyst** [comment]
On 08/07/15 11:47, Cornelis G. A. Kolbach wrote:

> If I remember well the notifications part (what you see when you
> click on the bell symbol in the global header) shows everything
> that directly applies to the user. For instance, somebody commented
> on an article which you also commented on before. Or somebody liked
> something that you have published before. The stream just shows
> everything that’s going on in Workspaces you have access to, or
> from people you follow.

In this case it means that if I'm following a workspace, or a folder, and somebody publishes new items there, I want to be notified of that change. If I don't want the notifications I should unfollow the context or unsubscribe from the event type ("item published"). This means that the to-be-realized control panel for notifications needs to not only control email notifications but should also afford filtering of web notifications.

**Comment by gyst** [comment]
On hold now, first we do content updates in the stream.

**Comment by gyst** [comment]
Related to #512

**Comment by mattss** [comment]
Superceded by https://github.com/quaive/ploneintranet/issues/1
