### ISSUE TITLE
Header style issues on delete confirmation modal

### ISSUE THREAD

**Issue by mattss** [ploneintranet/ploneintranet#363]
See conversation:

https://github.com/ploneintranet/ploneintranet/pull/349#issuecomment-118042339

Something odd is happening when pulling delete_confirmation into pat-modal on the document view, despite using exactly the same markup on event_view, where it works fine.

We may need a custom delete_confirmation page to resolve this.

**Comment by gyst** [comment]
See also #527 and #433

**Comment by reinhardt** [comment]
Note that adding a custom delete_confirmation doesn't seem to have fixed the issue. See #499

**Comment by ale-rt** [comment]
I think this can be closed after recent work on the delte form: 
- https://github.com/ploneintranet/ploneintranet/pull/650
- https://github.com/ploneintranet/ploneintranet/pull/674
- https://github.com/ploneintranet/ploneintranet/pull/675

**Comment by pilz** [comment]
Delete modals now look fine on both document and event, so I am closing this.
![bildschirmfoto 2015-08-27 um 16 09 16](https://cloud.githubusercontent.com/assets/138906/9522625/06d16f40-4cd6-11e5-9f1a-8e6d9991a345.png)
![bildschirmfoto 2015-08-27 um 16 08 54](https://cloud.githubusercontent.com/assets/138906/9522624/06cc5bb8-4cd6-11e5-83dd-b9da78c7582c.png)
