### ISSUE TITLE
Barceloneta: Sidebar JS broken on news view

### ISSUE THREAD

**Issue by pilz** [ploneintranet/ploneintranet#366]
On News Items, we see a javascript error 
TypeError: undefined is not a function (evaluating '$('.newsImageContainer a').prepOverlay({subtype: 'image'})')

The "a" doesn't have the prepOverlay function. This points to a loading or availability issue for the js containing the prepOverlay.

Next Step: Check if this is an upstream Plone regression first.

**Comment by gyst** [comment]
Is upstream bug
https://github.com/plone/Products.CMFPlone/issues/738
