### ISSUE TITLE
Userprofiles: Optional fields not configurable read_only

### ISSUE THREAD

**Issue by pilz** [ploneintranet/ploneintranet#368]
In PR "Editable user profiles #350" support was added to configure the user profile fields through the registry.

It just seems that only the mandatory fields respond to the read_only config, not the optional ones. 

![screen shot 2015-07-03 at 15 41 53](https://cloud.githubusercontent.com/assets/138906/8500208/2b73a19a-219a-11e5-85f4-93a748ba495b.png)
![screen shot 2015-07-03 at 15 41 38](https://cloud.githubusercontent.com/assets/138906/8500209/2b96907e-219a-11e5-8bd6-e0b5937de78e.png)

**Comment by mattss** [comment]
Aha - I'm pretty sure this is because the optional stuff is added via a behaviour, so you need to reference them with the behaviour class as a prefix:

IUserProfileAdditional.telephone
IUserProfileAdditional.mobile
etc.

**Comment by pilz** [comment]
Confirmed. That works fine.
