### ISSUE TITLE
Barceloneta: Cleanup

### ISSUE THREAD

**Issue by pilz** [ploneintranet/ploneintranet#376]
Now that we have the Themeswitcher, we need to clean it up to not confuse users. Hide as much as we can.
- Hide the news portlet
- Provide a sensible default for the workspaces, dashboard and apps section
- …

**Comment by pilz** [comment]
Related to / tackle together with  #440

**Comment by gyst** [comment]
Pull request in #613

I don't think this ticket is valid mostly - getting breakage is inherent in disabling our theme. Working around that is a strategy that ends up with the requirement for a fully functional  Barceloneta Plone Intranet which is what we have chosen NOT to do.

**Comment by gyst** [comment]
I actually reverted most of the work I did for this ticket, see commit log. Removing one layer of breakage just uncovers deeper and deeper layers of Barceloneta incompatibilities.
