### ISSUE TITLE
Search: subjects should be searched and boosted by default

### ISSUE THREAD

**Issue by gyst** [ploneintranet/ploneintranet#377]

**Comment by mattss** [comment]
Subject (tag) is currently searched by default (via SearchableText), but not boosted.

**Comment by gyst** [comment]
Boosting is configured in search/profiles/default/registry.xml

This breaks however because while the solr code provides a Subjects->tag mapping index-time the naming mismatch is not handled properly query-time.

Possible solution is to bring the solr schema in line with the zcatalog schema.

**Comment by gyst** [comment]
Fixed by #617
