### ISSUE TITLE
Invitation message as template

### ISSUE THREAD

**Issue by wengole** [ploneintranet/ploneintranet#40]
<a href="https://github.com/wengole"><img src="https://avatars.githubusercontent.com/u/383857?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wengole](https://github.com/wengole)**
_Monday Jan 19, 2015 at 12:02 GMT_
_Originally opened as https://github.com/ploneintranet/ploneintranet.invitations/issues/6_

---

Currently the invitation email body if hard-coded. We should ideally make this content that is editable somewhere.

**Comment by gyst** [comment]
This should be designed, not editable.

**Comment by wengole** [comment]
@gyst the date on this issue (that was imported to the new repo) is a lie. This issue is almost a year old. It originates from when Netsight started. We didn't have time to allow the invitation body text to be editable, so added a github issue to remind us.

This can probably be closed. As you say it needs to be designed, and when we get to the relevant story, I feel there's quite a few changes that are likely needed

**Comment by jcbrand** [comment]
This issue was moved to ploneintranet/ploneintranet.prototype#15
