### ISSUE TITLE
Add/edit richtext document and save shows two spinners

### ISSUE THREAD

**Issue by maartenkling** [ploneintranet/ploneintranet#401]

**Comment by ale-rt** [comment]
I would close this ticket as invalid, the behavior is the expected one.
Infact, we display a spinner for each target of pat-inject.
There are cases in which we see three spinners!
In addition spinner don't disappear if injection fails.

I would also prefer:
- some less "shocking" visual feedback
- a way to handle failures

I agree that this is not optimal but probably we should file a more general issue on patternslib.

**Comment by pilz** [comment]
I agree. Also we are about to change the pat-notification inject to a smaller note saying when the doc was saved on the top left. This will reduce this to only one spinner so that the problem will automatically go away.
