### ISSUE TITLE
Align buttons in editor do nothing?

### ISSUE THREAD

**Issue by maartenkling** [ploneintranet/ploneintranet#402]
<img width="61" alt="screen shot 2015-07-08 at 15 31 27" src="https://cloud.githubusercontent.com/assets/946684/8571343/725379d8-2586-11e5-80c1-ddd80b233dc9.png">

edit a page having text and hit the buttons?

**Comment by pilz** [comment]
passed to @cornae in ploneintranet.prototype ticket 108

**Comment by gyst** [comment]
https://github.com/ploneintranet/ploneintranet.prototype/issues/108

**Comment by pilz** [comment]
This is working now.
