### ISSUE TITLE
Event: Organiser/All day / Invitees not saved and coloured bullets?

### ISSUE THREAD

**Issue by maartenkling** [ploneintranet/ploneintranet#405]
when selecting them nothing happens, and what are these bullets?
<img width="487" alt="screen shot 2015-07-08 at 15 33 54" src="https://cloud.githubusercontent.com/assets/946684/8571443/2ac2a03e-2587-11e5-9f62-5cba1a8df1a8.png">

**Comment by pilz** [comment]
This is still to be implemented. Users can - when invited - state their attendance. Then the select pill is coloured like showin in the agenda.
We can either hide this field, implement at least the user picker (see #431) or implement it fully.

**Comment by gyst** [comment]
Hide labels for now, adding confirmation functionality is out of scope for now.

**Comment by gyst** [comment]
Fixed in #548
