### ISSUE TITLE
Stream comment injection removes already-existing comments (only visually)

### ISSUE THREAD

**Issue by maartenkling** [ploneintranet/ploneintranet#408]
sometimes you will see 2 items, sometimes none, refreshing shows all commenting again

**Comment by pilz** [comment]
What do I have to do to "leave comment 4 times"?

**Comment by gyst** [comment]
Sounds like a dupe of #74 which shouldve been fixed in #291 but maybe is not.

**Comment by gyst** [comment]
Injection error: new comment removes old comments.

**Comment by gyst** [comment]
The injection needs to be fixed. @ale-rt this one is for you :-)

**Comment by gyst** [comment]
I have the sources for the injection diagram documentation on my laptop so can provide an updated doc for that as soon as it's clear how it's changed.
