### ISSUE TITLE
Profile Person title show twice

### ISSUE THREAD

**Issue by maartenkling** [ploneintranet/ploneintranet#409]
as user add person title
as admin view
http://localhost:8080/Plone/profiles/rosalinda_roache
Name Mrs Mrs Rosalinda Roache

**Comment by pilz** [comment]
Seems fixed. I followed the steps and see it once.
<img width="418" alt="screen shot 2015-07-12 at 16 21 21" src="https://cloud.githubusercontent.com/assets/138906/8638164/162a585a-28b2-11e5-98d3-bf97b5f18906.png">
