### ISSUE TITLE
How to change my profile img?

### ISSUE THREAD

**Issue by maartenkling** [ploneintranet/ploneintranet#411]
not here;
http://localhost:8080/Plone/profiles/rosalinda_roache
and not here:
http://localhost:8080/Plone/@@personal-information
even as last page says: Portrait To add or change the portrait: click the "Browse" button; select a picture of yourself. Recommended image size is 75 pixels wide by 100 pixels tall.

**Comment by ale-rt** [comment]
Personal information (http://localhost:8080/Plone/@@personal-information) is gone after #513 
I am going to modify http://localhost:8080/Plone/profiles/rosalinda_roache#person-info

**Comment by gyst** [comment]
This needs to be scheduled as design first.

**Comment by ale-rt** [comment]
See https://github.com/ploneintranet/ploneintranet.prototype/issues/125

**Comment by pilz** [comment]
fixed in 1.1
