### ISSUE TITLE
as a user in workspace there is a (dot dot dot) button to add users or select, both do nothing

### ISSUE THREAD

**Issue by maartenkling** [ploneintranet/ploneintranet#414]
select will give option to remove ... but does nothing

**Comment by pilz** [comment]
The shere availability for normal users needs permission checking. 
This is also related to #338 where the add/remove functionality needs to be built first.

**Comment by gyst** [comment]
#528 is almost ready to merge and fixes #338. This ticket #414 would be a final permissions cleanup.

**Comment by reinhardt** [comment]
#338 already checks for permission to manage the roster and hides the select and add user/group buttons accordingly. I'll leave this open anyway in case someone wants to do a separate review.

**Comment by gyst** [comment]
Not correct. If you go to http://localhost:8080/Plone/workspaces/parliamentary-papers-guidance as allan_neece you're a plain member in a admin-managed workspace and still have the dot.dot.dot. menu with 'add user' and 'select'.

**Comment by reinhardt** [comment]
Well, yes, you do, but then again, allan_neece seems to have the "collective.workspace: Manage roster" permission. I've seen an "Admin" group in the workspaces, which might be where that comes from, but where is that exposed in the UI? How do I see who has admin rights on a workspace?

**Comment by mattss** [comment]
The admin group was built long before we had any UI, and is meant to contain the users who manage the workspace (and manage the membership of the workspace).

I've no idea if there even is any UI in the prototype for managing workspace admins, but you get that role automatically if you create a workspace.

**Comment by gyst** [comment]
This is a real security bug. allan_neece is only a team member, not an admin, for parliamentary-papers-guidance

**Comment by reinhardt** [comment]
I tested this again and now I don't see the extra elements as allan_neece. Don't think I changed anything. Perhaps this needs some more investigation and/or another test.

**Comment by gyst** [comment]
Sorry @reinhardt this is now part of #338 and #518  - @mattss is working on that already.

**Comment by mattss** [comment]
I can't replicate this on a fresh install. There are quite a few integration tests on this in ploneintranet.workspace, so I think it was specific your installation.
