### ISSUE TITLE
events and attachment

### ISSUE THREAD

**Issue by maartenkling** [ploneintranet/ploneintranet#416]
what does this button do?
<img width="505" alt="screen shot 2015-07-08 at 16 08 04" src="https://cloud.githubusercontent.com/assets/946684/8572232/990684ee-258b-11e5-8947-77519986bc40.png">

**Comment by pilz** [comment]
We have hidden the attached files function from events but not outcommented this attachment listing. Either the task is to implement the attachments now or also to outcomment the paperclip for now.

**Comment by gyst** [comment]
Hide the paperclip.
