### ISSUE TITLE
How to add a task on you dashboard?

### ISSUE THREAD

**Issue by maartenkling** [ploneintranet/ploneintranet#417]
as a user i can make tasks in workspace but they do not appear on dashboard?
doesnt dashboard tasks need a link to create one?

**Comment by pilz** [comment]
The dashboard should show tasks that are assigned to you. Did you assign that task to yourself?

**Comment by maartenkling** [comment]
yes i did, nothing happend

**Comment by pilz** [comment]
This does work for me as allan_neece. The only idea I have is that we have initiator and assignee, and you need to be in the assignee field. initiator is not taken into account.
<img width="416" alt="screen shot 2015-07-12 at 16 08 00" src="https://cloud.githubusercontent.com/assets/138906/8638119/37af94f6-28b0-11e5-9102-07efd69a7b56.png">

**Comment by pilz** [comment]
I found the reason. The tasks have another state "planned" which is set when it happens in a milestone not open yet. However this needs some more discussion on how to visualise better. For now I would then show open and planned tasks on the dashboard. This is going to be fixed in #556
