### ISSUE TITLE
adding people to comment does not show img

### ISSUE THREAD

**Issue by maartenkling** [ploneintranet/ploneintranet#419]
<img width="340" alt="screen shot 2015-07-08 at 16 11 34" src="https://cloud.githubusercontent.com/assets/946684/8572299/130f9190-258c-11e5-8446-7d5969e62a1a.png">

**Comment by pilz** [comment]
That seems to be fixed in the meantime. 
<img width="418" alt="screen shot 2015-07-12 at 16 04 20" src="https://cloud.githubusercontent.com/assets/138906/8638113/c0d018ce-28af-11e5-843a-752a700adb8a.png">
