### ISSUE TITLE
as a user when visiting a profile my breadcrums give me Profile link when hitting this get unauthorized

### ISSUE THREAD

**Issue by maartenkling** [ploneintranet/ploneintranet#420]
http://localhost:8080/Plone/profiles/christian_stoney
Hit Profiles
http://localhost:8080/Plone/acl_users/credentials_cookie_auth/require_login?came_from=http%3A//localhost%3A8080/Plone/profiles

**Comment by gyst** [comment]
This is because the profiles folder is private but should be published.
Partially duplicates #413 and #446
