### ISSUE TITLE
Some buttons on a page need permission checks (A page and his buttons)

### ISSUE THREAD

**Issue by maartenkling** [ploneintranet/ploneintranet#422]
http://localhost:8080/Plone/workspaces/open-market-committee/manage-information/public-bodies-reform
As a user, i have delete button and Insufficient Privileges popup, then a copy button? a share button showing: 
<img width="1037" alt="screen shot 2015-07-08 at 16 14 57" src="https://cloud.githubusercontent.com/assets/946684/8572367/813a86a2-258c-11e5-8753-31bcb6c00095.png">
etc

**Comment by fredvd** [comment]
Do we need to check on other buttons here, is allow to copy documents from a consume only workspace to another worksapace where  a use has edit rights?
