### ISSUE TITLE
Actions available to non-admins on events needs permission checks

### ISSUE THREAD

**Issue by maartenkling** [ploneintranet/ploneintranet#423]
http://localhost:8080/Plone/workspaces/open-market-committee/manage-information/public-bodies-reform
as a user it looks like i can edit but cant and buttons on right to give errors
<img width="1233" alt="screen shot 2015-07-08 at 16 18 03" src="https://cloud.githubusercontent.com/assets/946684/8572443/e9dafc78-258c-11e5-9546-50e094505db4.png">

**Comment by gyst** [comment]
Related to #424

**Comment by gyst** [comment]
Fixed in #551

**Comment by gyst** [comment]
Duplicates #416 fixed in #548
