### ISSUE TITLE
As a user i have a bin icon to remove events i dont own

### ISSUE THREAD

**Issue by maartenkling** [ploneintranet/ploneintranet#424]
<img width="420" alt="screen shot 2015-07-08 at 16 18 54" src="https://cloud.githubusercontent.com/assets/946684/8572469/17774330-258d-11e5-83bf-a5d413e4b944.png">

**Comment by gyst** [comment]
This should only be possible if you own the event or are in a 'moderator' workspace, which Open Market Committee is not.

**Comment by gyst** [comment]
PR for this is #551
