### ISSUE TITLE
profile images are incorrect

### ISSUE THREAD

**Issue by maartenkling** [ploneintranet/ploneintranet#427]
http://localhost:8080/Plone/profiles/allan_neece

^^ these images have a gray border as others have not
<img width="286" alt="screen shot 2015-07-08 at 16 24 40" src="https://cloud.githubusercontent.com/assets/946684/8572640/f2a7fe18-258d-11e5-9a63-3430a90cecf7.png">

**Comment by mattss** [comment]
This is also the case in the prototype - see http://prototype.ploneintranet.net/liz-baker/

**Comment by maartenkling** [comment]
then prototype is also wrong :)

**Comment by mattss** [comment]
Agreed - I was actually suggesting this ticket should be raised in the prototype repo instead: https://github.com/ploneintranet/ploneintranet.prototype/

**Comment by pilz** [comment]
I am not sure but it might already be fixed as I don't find any images in proto without the gray border. Can you recheck and point to one without in case I'm wrong?

**Comment by mattss** [comment]
To reproduce:
- Go to http://prototype.ploneintranet.net/liz-baker/
- Scroll down to 'Followers' on LHS
- Most of the avatars have grey gap/border on the left and right sides. 

These gaps/borders appear to be specific to the followers/following avatars on the user profile. They do not appear on the main profile image, or in avatars that appear in the activity stream.

**Comment by pilz** [comment]
Ah, now I see it. The profile image under "Followers" seems to not fully fill the gray circle. There is a max-width:90% on the div.document img which should probably be disabled when within .pat-avatar.

**Comment by allcaps** [comment]
The image isn't square. But should be.

**Comment by pilz** [comment]
Ah, good catch. Yes, Cornelis wants for a long term now a squarification for profile images. I wonder if we can use p.a.imaging and cropping support to crop them automatically?

**Comment by mattss** [comment]
Avatar images are already cropped using p.a.imaging (see https://github.com/ploneintranet/ploneintranet/blob/master/src/ploneintranet/userprofile/browser/userprofile.py#L90)

**Comment by allcaps** [comment]
Ooops. It's not the size if the image. The images are square. The css adds `max-width:90%;`
Lives in _document-body.scss line 99. But this styles other elements as well.

@cornae ^^^

**Comment by mattss** [comment]
Moved this issue to the prototype repo: https://github.com/ploneintranet/ploneintranet.prototype/issues/118
