### ISSUE TITLE
Event vocabolaries

### ISSUE THREAD

**Issue by massimoazzolini** [ploneintranet/ploneintranet#431]
The fields organizer, invitees, and "Attached documents from this workspace" let you search for people and documents, but nothing is found.

![image](https://cloud.githubusercontent.com/assets/883251/8573523/50a8702a-2592-11e5-8dd4-0a6303295dba.png)

**Comment by ale-rt** [comment]
Note to myself
I have to implement the pat-autosuggest source.
- https://github.com/Patternslib/Patterns/blob/master/src/pat/auto-suggest/documentation.md

**Comment by pilz** [comment]
fixed by #605
