### ISSUE TITLE
Event timezone

### ISSUE THREAD

**Issue by massimoazzolini** [ploneintranet/ploneintranet#432]
it shows only three places:

![image](https://cloud.githubusercontent.com/assets/883251/8573550/7c7bf168-2592-11e5-9a02-dd8317f97063.png)

**Comment by gyst** [comment]
See also #476. This may be both a UI bug (not showing the full menu) and a backend bug (timezone support).

**Comment by ale-rt** [comment]
Note to myself
The timezones are actually three in the source code
- https://github.com/ploneintranet/ploneintranet/blob/master/src/ploneintranet/workspace/browser/templates/content_macros.pt#L116
  We probably want to use: 
- https://github.com/plone/plone.app.vocabularies/blob/1ecde46aadddadeb143baa5c479540297eb7ac80/plone/app/vocabularies/configure.zcml#L107

**Comment by gyst** [comment]
Which makes this ticket part of #431 event vocabularies

**Comment by cillianderoiste** [comment]
We use a custom widget for dates https://github.com/ploneintranet/ploneintranet/blob/master/src/ploneintranet/workspace/basecontent/widgets.py#L74 and I suspect we can add an extra input with the name "start" which has the timezone. The extract method can then parse that. For the end date we'd need to copy that value to a hidden field with the name "end". I wonder if we can use a pattern to do that (pat-clone?).

Maybe there's a more clever way to handle this, but when I was working on the date widget this was what I had in mind.

**Comment by ale-rt** [comment]
Nice advice! Thank you @cillianderoiste!
