### ISSUE TITLE
Event deletion land on workspace home

### ISSUE THREAD

**Issue by massimoazzolini** [ploneintranet/ploneintranet#433]
After the confirmation of a deletion of an event, it reloads the page and lands on workspace's home (http:/localhost:8080/ploneintranet/workspaces/open-market-committee) the event panel is closed and you have to re-open it

**Comment by gyst** [comment]
related to #527

**Comment by gyst** [comment]
I'm not sure we want to fix this right now. There's a bigger story about managing the combined sidepane / main pane state. Also plays out with deeplinks.
