### ISSUE TITLE
Event: dates check

### ISSUE THREAD

**Issue by massimoazzolini** [ploneintranet/ploneintranet#434]
you can save an event:
- without entering any date (and you cannot find it anymore)
- having the start date that happens after the end date

**Comment by pilz** [comment]
Date fields are now preset. which greately reduces the chance of accidentally misfilling.
However we should have validation in place that complains in case someone deliberately removes the dates and if they are in no proper order. That could be achieved with pat-validation.

**Comment by pilz** [comment]
#481 validates the title and start/end fields properly. However validation whether an end date is before a start date is irritatingly difficult with parsley at the moment. We have looked at using validate.js, which is applying validation in a declarative way and that would be much better and more flexible. But at this point this would cost probably a few days to properly implement and test and switch, so I'd say we skip that for later.

**Comment by gyst** [comment]
Work in progress on #481. Closing this as duplicate.
