### ISSUE TITLE
"Group by folder" wraps the search in subfolders

### ISSUE THREAD

**Issue by massimoazzolini** [ploneintranet/ploneintranet#436]
![image](https://cloud.githubusercontent.com/assets/883251/8574285/33e1f5c0-2596-11e5-968b-94b994ae0133.png)

vs

![image](https://cloud.githubusercontent.com/assets/883251/8574291/3e2194dc-2596-11e5-9d24-3becb8a6bc3e.png)

**Comment by pilz** [comment]
Should be fixed by #439
