### ISSUE TITLE
opening a document in expanded view doesn't show up

### ISSUE THREAD

**Issue by massimoazzolini** [ploneintranet/ploneintranet#437]
go here:
![image](https://cloud.githubusercontent.com/assets/883251/8574330/66a237c2-2596-11e5-9999-c9640d0dfe18.png)

open "budget proposal". 
It has been actually opened, but it's hidden behind the view. collapse it and you'll see it:

![image](https://cloud.githubusercontent.com/assets/883251/8574389/aac47910-2596-11e5-8445-3f38bdb7e24b.png)

**Comment by pilz** [comment]
Fixed by #461
