### ISSUE TITLE
When anon i see navigation 

### ISSUE THREAD

**Issue by maartenkling** [ploneintranet/ploneintranet#441]
as anon view login page in html is

nav class="tabs navigation pat-bumper" id="home-tabs" style="position: relative;">
                  a href="http://localhost:8080/Plone" title="" class="current">Dashboard</a>

```
              a href="http://localhost:8080/Plone/workspaces" title="">Workspaces</a>

              a href="http://localhost:8080/Plone/library" title="">Library</a>
          /nav>
```

**Comment by maartenkling** [comment]
see http://localhost:8080/Plone/folder_listing

**Comment by ale-rt** [comment]
Sorry I closed this committing directlyu to master :/

**Comment by ale-rt** [comment]
Can anybody validate it is working now?

Sorry again for committing to master :(

**Comment by allcaps** [comment]
Confirmed, the menu items are gone.
