### ISSUE TITLE
toggle side bar layout is incorrect

### ISSUE THREAD

**Issue by maartenkling** [ploneintranet/ploneintranet#445]
http://localhost:8080/Plone/workspaces/open-market-committee

im able to select items? and then?
link is incorrect
<img width="1238" alt="screen shot 2015-07-08 at 19 55 40" src="https://cloud.githubusercontent.com/assets/946684/8577795/5f41782a-25ab-11e5-8ade-db51178ac084.png">

**Comment by pilz** [comment]
In PR #461 the sidebar becomes small again when you click an item. That should fix it.

**Comment by gyst** [comment]
This is a proto bug - (multi) selection should only be possible in batch editing mode.

**Comment by pilz** [comment]
I am no longer able to select items in the extended view. Can somebody still reproduce this?

**Comment by gyst** [comment]
I can reproduce, but only in proto. First open batch select, then select two items, then leave batch select mode. The two items are still selected.

This risks popping up in dev as soon as #579 is fixed and we get batch actions in dev.

**Comment by gyst** [comment]
Actually I can reproduce in dev.
Login as christian_stoney, go to http://suite.ploneintranet.net/workspaces/open-market-committee.
Expand sidebar.
Click functions menu (dot.dot.dot) open. 
Click functions menu closed.
You can select multiple items.
The selection persists after page reloads (!) and also when contracting the sidebar.

**Comment by pilz** [comment]
Ok, at least now we have bulk editing in the sidebar so that you can select and deselect properly. 
It may me un-nice to see two selected items when exiting bulk mode, but it doesn't really harm anymore. 

So what should happen instead? Should exiting bulk mode deselect everything?

**Comment by gyst** [comment]
Yes, exiting bulk selection should unset the selection.

**Comment by gyst** [comment]
This is harmless, moving back to the backlog.
