### ISSUE TITLE
no way to see all members?

### ISSUE THREAD

**Issue by maartenkling** [ploneintranet/ploneintranet#446]
localhost:8080/Plone/profiles/ is undesigned

most awful example but something like: http://www.simpleintranet.org/wp-content/uploads/2013/11/employee-grid2.gif

**Comment by pilz** [comment]
related to #420

**Comment by gyst** [comment]
Out of scope for now.

**Comment by gyst** [comment]
This would need to become something like a user management app, separate from "contacts", in which one can set security settings and the like. But it may also be something integrated in other apps, e.g. if the "news cms" and "library cms" enable the selection of users for specific roles within that app, we don't need any global role setting.

**Comment by gyst** [comment]
NB viewing users can be done already via people search.

**Comment by gyst** [comment]
Superseded by #755, partially fixed in #770.
