### ISSUE TITLE
unable to edit word file in workspace 

### ISSUE THREAD

**Issue by maartenkling** [ploneintranet/ploneintranet#451]
http://localhost:8080/Plone/workspaces/open-market-committee/manage-information/minutes/view

how to edit the file? and replace it?

**Comment by pilz** [comment]
We need to
- Enable the external editor feature (I propose by default)
- Probably should provide a download link to the client component somewhere
- Add a file widget to the file metadata to upload a new file

**Comment by gyst** [comment]
These are two separate issues. I think externaleditor should NOT be enabled by default. That's an integrator's choice to enable, depending on the client IT landscape.

Which means we do need the extra upload widget to replace an existing file.
@cornae can you please add another icon to the meta bar?

**Comment by gyst** [comment]
So this is about the upload icon.

External editor icon is discussed in
https://github.com/ploneintranet/ploneintranet.prototype/issues/77

**Comment by cillianderoiste** [comment]
I'll add the file widget to files and images.

**Comment by cillianderoiste** [comment]
I've added the fields in #626, I'll leave the rest to @cornae
