### ISSUE TITLE
button help on mouseover

### ISSUE THREAD

**Issue by maartenkling** [ploneintranet/ploneintranet#453]
there are many buttons, they all need help test on mouseover, i have no idea what they are

<img width="853" alt="screen shot 2015-07-08 at 21 17 43" src="https://cloud.githubusercontent.com/assets/946684/8579762/c6355802-25b6-11e5-8737-81e010751b4e.png">

**Comment by pilz** [comment]
duplicate or related to #336

**Comment by pilz** [comment]
All UI elements should have a title attribute

**Comment by gyst** [comment]
PR is #528. Please don't separate submit the original ticket for review...
