### ISSUE TITLE
Cant view Event items

### ISSUE THREAD

**Issue by maartenkling** [ploneintranet/ploneintranet#454]
http://localhost:8080/Plone/workspaces/open-market-committee/past-event#document-body
and
http://localhost:8080/Plone/workspaces/open-market-committee/future-event#document-body

are available for admin
but not for user rosalinda_roache

no indication why or what ever

**Comment by pilz** [comment]
On a current portal, I can see and open events as rosalinda. Can you explain what you are missing?

**Comment by gyst** [comment]
Any dev: please try to reproduce and either fix or close as invalid.

**Comment by ale-rt** [comment]
The fact is that "Past event":
- http://localhost:8080/Plone/workspaces/open-market-committee/past-event

is in a draft state.

If I log as admin I can see it.
If I log in as rosalinda i get an unauthorized

Apparently Rosalinda sees only the published events.

@gyst, @pilz, do you think this is the correct behaviour?

If this is the case we may want to close the issue as invalid.

Maybe we could open (if not already there) another issue asking to provide a better visual feedback for the content state.

**Comment by gyst** [comment]
Thanks Ale, closing now.
