### ISSUE TITLE
Task tagging should load tag suggestions

### ISSUE THREAD

**Issue by maartenkling** [ploneintranet/ploneintranet#457]
create a todo task and view
the i button for tags does nothing but show text: tags

**Comment by pilz** [comment]
The text is a placeholder, the field is a select2 autocomplete. Work is currently ongoing to integrate the autosuggest backend.

**Comment by gyst** [comment]
Tagging fixed in #470

**Comment by gyst** [comment]
Confirmed. Create a todo, then edit it's metadata. Tag suggestions are not loaded.
