### ISSUE TITLE
case templates bootstrapping

### ISSUE THREAD

**Issue by gyst** [ploneintranet/ploneintranet#462]
This follows up on #292 

The main problem is, that this now hard requires templates to be configured, but:
- no templates are available in a default install (only in testcontent)
- there's no (documented) way to create a template TTW

In short, if we follow Maarten's procedure, and install an empty Plone Intranet site, this results in a broken product. 
1. We need documentation on how to configure templates from scratch.
2. Currently you cannot create a template TTW without a template...
   
   (a.) either we make it possible to bootstrap TTW, e.g. with sane defaults
   
   (b.) or we hide all "Cases" functionality unless templates are available (from a custom setup handler)

My guess is that 2a. is easier than 2b. It's also more elegant since 2b. requires integrators to write custom code before they can even use this part of the product.

**Comment by gyst** [comment]
Sane defaults could be implemented by changing the conditional here:
https://github.com/ploneintranet/ploneintranet/blob/master/src/ploneintranet/workspace/subscribers.py#L62

**Comment by cillianderoiste** [comment]
Thanks for the review!

I guess another option is to create and configure an example Template Case in the workspace setuphandlers: https://github.com/ploneintranet/ploneintranet/blob/master/src/ploneintranet/workspace/setuphandlers.py#L30

Let me know which option you prefer and I can implement it and add some documentation for integrators which describe how to create additional Case Templates and configure them (via the ZMI). Does that sound OK?

I do wonder if there is a plan in the future to create a user interface for managing cases. Perhaps it would also be a powerful feature for intranet admins.

**Comment by gyst** [comment]
@cillianderoiste I'd like a hardcoded fallback template to be available at all times. Templates living in content space are easily damaged by content editors; providing a code level fallback makes the system resilient and allows user to recover from errors.

**Comment by cillianderoiste** [comment]
OK, that sounds good.

**Comment by gyst** [comment]
Fixed in #773
