### ISSUE TITLE
Make open/close state of tasks and tick box state in sync

### ISSUE THREAD

**Issue by cornae** [ploneintranet/ploneintranet#47]

**Comment by adrianwhite** [comment]
#61 ensures the state selector when view a task and the task in the sidebar have the appropriate open/closed and unchecked/checked setting.

To have one update the other when interacting I am not sure what pattern(s) to us. The closest I can see would be pat-switch but this only acts upon classes and not checked/selected attributes.

What do you suggest @cornae and @jcbrand

**Comment by cornae** [comment]
I say inject in some form. Possibly with the addition of pat-subform.

**Comment by jcbrand** [comment]
This issue was moved to ploneintranet/ploneintranet.prototype#14
