### ISSUE TITLE
ZCatalog search requires KeywordIndex for filters

### ISSUE THREAD

**Issue by mattss** [ploneintranet/ploneintranet#478]
The current zcatalog search filter implementation is not compatible with the UI search filters unless you use a KeywordIndex, because the UI always generates a list.

The solr implementation turns this list into an 'OR' statement, but the zcatalog one just passes it straight through to the catalog (as the zcatalog has no built-on OR support). This works for KeywordIndex but not FieldIndex.

The interrim solution is to:
a) use SOLR 
b) use a KeywordIndex

It should be possible to update the zcatalog implementation to resolve this, (using [Products.AdvancedQuery?](http://docs.plone.org/develop/plone/searching_and_indexing/query.html#boolean-queries-advancedquery) )

**Comment by mattss** [comment]
fyi @gyst @cillianderoiste

**Comment by gyst** [comment]
c) disable facets for zcatalog implementation

**Comment by mattss** [comment]
To clarify - this is an issue with _filtering_, not _faceting_. In the way they are used in pi.search, filters are any options you pass in to generate search results, and facets are the available options generated _from_ your existing set of search results, which can be used to further refine/group the results.

Getting the available facets out of search results is supported out of the box in solr, and we manually generate it in the Plone implementation. Both of these work fine.

What doesn't work with the zcatalog at the moment is the 'OR' nature of the search UI, where the options on the LHS are always lists of items (e.g. tags), and we expect to get back results matching _any_ of the tags, rather than ones that match _all_ the tags.

So to disable this feature in the zcatalog implementation, we would have to drop the left hand side of the search page and just have a keyword search.

**Comment by gyst** [comment]
@mattss Thanks for the clarification. That basically destroys ZCatalog as a viable backend but we always aimed for Solr. I'd rather not spend resources on monkeying to support ZCatalog, and Products.AdvancedQuery looks like a risk. Please disable the left hand side filters for ZCatalog for now. A workaround would be to change the UI to only support one option at a time (effectively replacing the checkboxes with radios) but I'm sure @cornae would not agree and he's right. But even if it was an option I wouldn't want to spend resources on it.

What I _do_ think important given all of this, is that we display a warning if ZCatalog is used.
"You're using a fallback search engine. Please contact your site admin to get the fully-featured Solr search enabled."

**Comment by mattss** [comment]
@gyst My suggestion here is that we actually just disable _extra_ filters in ZCatalog implementation. The default out-of-the-box ones (friendly type and tags) are keyword indexes anyway, so we can keep this functioning like the prototype. We can then add some stuff to prevent you registering any extra filters if using the zcatalog - possibly showing a message under the default filters if you try to do so.

**Comment by gyst** [comment]
Oh that's better than I hoped for. Go ahead.

**Comment by gyst** [comment]
Doesn't require code IMO just a warning in the docs. I will do that, you can review.

**Comment by pilz** [comment]
we are not supporting zcatalog anymore, so should we close this? @gyst

**Comment by gyst** [comment]
It's a documentation task for me (that you need to run Solr for /extra/ filters) so please keep it open for me.
