### ISSUE TITLE
Breadcrumbs inconsistant

### ISSUE THREAD

**Issue by maartenkling** [ploneintranet/ploneintranet#489]
in workspaces: 
Toggle menuSiteWorkspacesService announcementsGuido Stevens  Search
on dashboard:
nothing
on library 
|
on search
nothing

**Comment by gyst** [comment]
See prototype for how it's supposed to work.
workspaces | aworkspace
library

**Comment by pilz** [comment]
related to https://github.com/ploneintranet/ploneintranet.prototype/commit/92302e68edcb737a8c730b3202b3274d3d7fde19#commitcomment-12157477

**Comment by gyst** [comment]
Proto is broken in this regards.
Should be always first level, in workspaces two levels.

**Comment by gyst** [comment]
PR #518
