### ISSUE TITLE
Create buildout.d directory

### ISSUE THREAD

**Issue by wengole** [ploneintranet/ploneintranet#49]
There are quire a lot of buildout configs now. To keep the root of the project tidy, @cillianderoiste and I discussed having a buildout.d directory

**Comment by pilz** [comment]
We have one now

**Comment by wengole** [comment]
That's good then. 😀

Wondered why I was getting a whole load of ploneintranet emails, this issue was created by me!

**Comment by pilz** [comment]
Hehe, you will get more, probably. Major cleanup ahead!
