### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by maartenkling** [ploneintranet/ploneintranet#491]
There is code in the HTML for a logo

a id="site-logo" href="http://localhost:8080/Plone" class="logo">
    img src="http://localhost:8080/Plone/++theme++ploneintranet.theme/generated/media/logo.svg" alt="Site">/a>

But this doest shows up

**Comment by ale-rt** [comment]
The fact is that the logo is an svg and we do not define a proper sizing for it.

If I specify a width of 120px, I can see the logo, 

```
<img src="http://localhost:8080/Plone/++theme++ploneintranet.theme/generated/media/logo.svg" alt="Site" style="
    width: 120px;
">
```

but the result is really poor:

![pilogo](https://cloud.githubusercontent.com/assets/1300763/8649506/4d00375a-296b-11e5-895b-6b899bcdac9c.png)

**Comment by pilz** [comment]
@cornae We lost a logo, have you seen it?

**Comment by cornae** [comment]
There's reference a to logo.svg in the markup on dev. This is wrong. Contrast to proto, where you see only the 'Site title' (a variable used in more places, including in the title tag). The brand SASS might or might not replace this text with an image.
