### ISSUE TITLE
Loginform it asking me for emailadres but login is username rosalinda_roache

### ISSUE THREAD

**Issue by maartenkling** [ploneintranet/ploneintranet#493]
or username should be email, or text should change

**Comment by allcaps** [comment]
What is the desired behaviour? A text change is little effort. Or should this be configurable?

Some guidance please.

**Comment by gyst** [comment]
Desired behavior is to ask for "E-mail address" if login by email is enabled, else ask for "Login name". Login by email is a site setting managed via generic setup.

**Comment by mattss** [comment]
Be aware that we are using dexterity.membrane for users. I know this has some configuration options for using email addresses to log in, but I'm not sure how/if it overlaps with plone's default email login setup. Needs investigation.

**Comment by gyst** [comment]
If you didn't set up email logins on membrane then we don't have it. I've done sites that have it and the upstream template code is incomplete. @allcaps so just hardcode "Login name" for now please.
