### ISSUE TITLE
Cant edit stream content

### ISSUE THREAD

**Issue by maartenkling** [ploneintranet/ploneintranet#494]
When making a post, im not able to edit or delete my post

**Comment by allcaps** [comment]
There is no design yet. The prototype has an cog icon. My best guess it that edit and delete should be options in some cog item menu. There is no design yet. I opened a prototype issue https://github.com/ploneintranet/ploneintranet.prototype/issues/124

**Comment by pilz** [comment]
fixed in 1.1
