### ISSUE TITLE
hashtags not linked

### ISSUE THREAD

**Issue by gyst** [ploneintranet/ploneintranet#501]
Post with comment does not link manual hashtag

**Comment by ale-rt** [comment]
This turns out to be interesting.
Parsing hashtags can require some work.
Probably we need to depend on some external library, e.g.:
- https://github.com/edburnett/twitter-text-python/blob/master/ttp/ttp.py#L98

**Comment by ale-rt** [comment]
I have a working prototype that uses that library to parse:
- users
- tags
- urls

IMHO We definetely want that functionality and rewriting everything from scratch is reinventing the wheel

Check this out:
- https://github.com/ploneintranet/ploneintranet/compare/501-render-hashtag

The code is not clean and no verification is done on the links but we can already achieve a result like this:
![image](https://cloud.githubusercontent.com/assets/1300763/8652829/298f5876-2981-11e5-83fa-8e91ada0d908.png)

**Comment by gyst** [comment]
Nice feature but it opens a can of problems that we don't have the manpower to tackle now.
- We miss a design for /@@stream/tag/foo and it shows
- Mentions inserted via the user picker _show_ the username but _link_ to the userid. We never show the userid.
- Mentions inserted via the user picker are indexed, mentions directly inserted not
- Tags inserted via the tag picker may contain spaces, tags inserted directly can not.

Additionally, inserting a userid inserts a link but it links the following text rather than the actual user. But I don't want users to have to worry about user ids, they should see only actual real people names.

For all these reasons we need actual shortcode support that uses the contentmirror. In the future.

Sorry for all the work you put in :-(
