### ISSUE TITLE
Transifex to Plone, translations in context

### ISSUE THREAD

**Issue by allcaps** [ploneintranet/ploneintranet#507]
I'm making the Dutch translation via Transifex and like to see my translations in context. So I downloaded the .po file form Transifex. This file contains all strings, but in Ploneintranet the .po files are split up per module.

Am I missing something? 

Ping: @pilz

**Comment by pilz** [comment]
Uh, split up per module, where do you see that? I thought we have all in core/locales. When I update the german translations, I place the ploneintranet.po file there and check it in. What you see may be a reminiscence from older days, perhaps a cleanup task. Can you point me to that?

**Comment by allcaps** [comment]
My bad. socialsuite, activitystream, microblog still have locales folders. So I was confused. Should those be dropped?

**Comment by pilz** [comment]
ok, need to check with @gyst whether these can be deprecated…

**Comment by gyst** [comment]
Please ignore the plonesocial legacy stuff. We need a bigger cleanup there, I'd rather do that in one go.
