### ISSUE TITLE
Implement a ContentStatusUpdate

### ISSUE THREAD

**Issue by ale-rt** [ploneintranet/ploneintranet#512]
This will be a special status update that has a reverence to a content_context (through IUUID).
This is part of the work for #359 

This is based on PR #511

**Comment by mattss** [comment]
WIP branch: https://github.com/ploneintranet/ploneintranet/compare/512-content-status-update

**Comment by mattss** [comment]
Superceded by https://github.com/quaive/ploneintranet/issues/1
