### ISSUE TITLE
Fix optional parameter context in StatusUpdate

### ISSUE THREAD

**Issue by ale-rt** [ploneintranet/ploneintranet#516]
See discussion in PR #511
https://github.com/ploneintranet/ploneintranet/pull/511#discussion-diff-34582003

**Comment by gyst** [comment]
Merged

**Comment by ale-rt** [comment]
At the end it is still like this:
- https://github.com/ploneintranet/ploneintranet/blob/master/src/ploneintranet/microblog/statusupdate.py#L33

I am going to fix it on a separate PR
