### ISSUE TITLE
Cancelling a delete confirmation in workspace destroys its view

### ISSUE THREAD

**Issue by fredvd** [ploneintranet/ploneintranet#527]
When I go into the Open Market Committee workspace as allan_neece,
navigate to manage information / Budget ProposaI,
press the delete button
and cancel the delete confirmation request modal:

I only see the budget proposlal image centered on screen and all surrounding navigation/workspace information is gone. 

![delete-confirmation-cancel](https://cloud.githubusercontent.com/assets/394784/8696132/1a92ad18-2aea-11e5-9918-bee98548a0e9.gif)

**Comment by ale-rt** [comment]
This is an upstream bug in plone/plone.app.content#38
