### ISSUE TITLE
robotframework tests cause "firefox unexpectedly quits" errors

### ISSUE THREAD

**Issue by fredvd** [ploneintranet/ploneintranet#534]
When running the ploneintranet.suite robotframework tests crash firefox startups, but the tests still run. 
Upgrading to selenium 2.46.0 from 2.45.0 fixes this.

**Comment by gyst** [comment]
This causes more breakage than it fixes. Probably better to downpin your local firefox?

**Comment by gyst** [comment]
Appears to be a mac-specific fix. On hold for now.
