### ISSUE TITLE
solr search finds only user profiles no content

### ISSUE THREAD

**Issue by gyst** [ploneintranet/ploneintranet#549]
- build solr
- install site with test content
- search 'allan' finds allan_neece
- search 'min' does not find anything

Same sequence on a non-solr build shows two search results in 'all results' for 'minutes'

**Comment by gyst** [comment]
@mattss on investigating this I'm convinced it's a duplicate of the issues we're seeing in #338 and #518 - as zope admin user I can see the items fine. When I test with christian_stoney (which is workspace admin) I do not see workspace content - appears to be an allowedUsersAndRoles issue.

Interestingly allan_neece _does_ see the workspace content so it's specific to the workspace admin!

**Comment by mattss** [comment]
@gyst Can you clarify whether or not this is actually solr-related? #338 and #518 don't relate to solr at all so I'm a little confused.

**Comment by mattss** [comment]
Found the issue. Fixing.
