### ISSUE TITLE
Error modifying an event date

### ISSUE THREAD

**Issue by ale-rt** [ploneintranet/ploneintranet#561]
Use case: I go in a workspace, I choose an event and try to modify its date.

Saving fails because of this:

```
2015-07-17 09:26:36 ERROR Zope.SiteErrorLog 1437117996.260.906759187998 http://localhost:8080/Plone/workspaces/open-market-committee/manage-information/plone-conf/event_view
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module ploneintranet.workspace.basecontent.baseviews, line 33, in __call__
  Module ploneintranet.workspace.basecontent.baseviews, line 60, in update
  Module ploneintranet.workspace.basecontent.utils, line 103, in dexterity_update
TypeError: can't compare offset-naive and offset-aware datetimes
```

The users keeps seeing the spinner and has no visual feedback of what is happening.

**Comment by ale-rt** [comment]
It turns out it is an issue of the generated content.
@gyst should we accept dates with no timezone associated?

Anyway I am fixing the setuphandler to create events with a timezone associated.

**Comment by ale-rt** [comment]
Related also to #432

**Comment by pilz** [comment]
I think fixing the setuphandler is sufficient. Through the interface it is no longer possible to create events without a TZ.

**Comment by gyst** [comment]
+1
