### ISSUE TITLE
Visual feedback when pat-inject fails

### ISSUE THREAD

**Issue by ale-rt** [ploneintranet/ploneintranet#562]
When pat-inject fails (e.g. #561) there is no sane fallback for the user.
An error message should be displayed.

**Comment by gyst** [comment]
No. We should fix the underlying backend bugs.

**Comment by ale-rt** [comment]
For sure the bugs should be fixed, but IMHO a fallback has to be there...
Anyway IMHO this either a problem of pat-inject or the way we are using it.

Maybe @cornae can say is opinion on this topic.

**Comment by jcbrand** [comment]
I agree with @ale-rt. Even if all bugs are fixed, there might be a 404 due to network issues. Ideally there should be a way to inform the user that the operation failed. I don't consider it a very high priority though.

**Comment by cornae** [comment]
A solution was created for this for a totally different project by @wichert, that allows you to give some feedback to the user when the feedback contains a 404 or another error. It's used by a Dutch government site that uses Patternslib: http://www.overstroomik.nl 

I believe it's part of stock Patterns and if not then we should make it stock Patterns. Is there anything to be found in the technical documentation or in the code of pat-inject on this?

**Comment by jcbrand** [comment]
I created a ticket in ploneintranet.prototype for this.
