### ISSUE TITLE
Get jenkins to run solr tests

### ISSUE THREAD

**Issue by gyst** [ploneintranet/ploneintranet#565]
Needed before #303 makes sense

**Comment by mattss** [comment]
Jenkins now runs the solr tests for ploneintranet.search whenever a change to master occurs:

http://jenkins.ploneintranet.net/job/solr.Ploneintranet.master/

**Comment by gyst** [comment]
Can we please turn that into a full test run that also includes ploneintranet.suite?
I'd like to be able to leverage the suite testcontent for robot tests.

**Comment by mattss** [comment]
Ah yes, sorry. Will  look into that.
