### ISSUE TITLE
Need dev.ploneintranet.net

### ISSUE THREAD

**Issue by gyst** [ploneintranet/ploneintranet#568]
@cornae needs to be able to inspect a running Plone instance that is up to date on master, so he can replicate UI bugs we're seeing and provide prototype solutions for those.

**Comment by gyst** [comment]
@pilz you mentioned it would not be that hard to run this? Please let me know if this is easy, and which DNS record I should create.

**Comment by pilz** [comment]
suite.ploneintranet.net still exists. I updated the underlying server just now.

**Comment by pilz** [comment]
It is the same server that also services proto and docs, so it runs a pull and buildout every 5 mins. If there are updates that break an existing database without upgrade steps, we will notice that here of course and need to manually update it.

**Comment by cornae** [comment]
That’s great. Can I have some credentials to use it?

**Comment by cornae** [comment]
Got credentials now. When I click through it I see a lot of little things. For some of these things there are maybe already tickets. What should I do when I see things? Wait till I’m back from holidays? Reading to every existing ticket takes too much time for now but I also don’t want to create duplicates.

**Comment by pilz** [comment]
You can just send me a long list and I can split it up in tickets

**Comment by cornae** [comment]
With keywords? And then you can ask for a more elaborate ticket text when you think it’s an unnoticed issue?

**Comment by pilz** [comment]
I can't validate that today, so perhaps its better you just create tickets as you go and we clean up if we find duplicates? You should certainly not waste time by looking for existing tickets

**Comment by cornae** [comment]
Assign them to you?

**Comment by pilz** [comment]
yes, fine
