### ISSUE TITLE
Demo social content changes after 5 minutes of applying demo content profile

### ISSUE THREAD

**Issue by bfackland** [ploneintranet/ploneintranet#569]
To re-produce:

1) buildout, create Plone site, import demo content profile as per docs (http://docs.ploneintranet.org/installation/development.html)
2) wait for 3-5 seconds after profile imported, just to make sure it's committed
3) log in as allan_neece and view the homepage - note the first post is Christian "draft for my presentation of Saturday":

<img width="500" alt="screen shot 2015-07-17 at 11 47 47" src="https://cloud.githubusercontent.com/assets/2538526/8744988/bac83310-2c7b-11e5-811d-0e21a1f73a3d.png">

4) after more than 5 minutes, reload the homepage - the first post is now Rosalinda lorem ipsum:

<img width="500" alt="screen shot 2015-07-17 at 11 47 56" src="https://cloud.githubusercontent.com/assets/2538526/8745011/eeea9bba-2c7b-11e5-95f9-a414ba19c5cd.png">

5) note that the time difference between top posts is 5 minutes; if you continue to reload the homepage the state now remains constant;

6) if you go to Christian's profile, the original post ("draft for my presentation of Saturday") still exists, but it's just older and not shown on the homepage:

<img width="500" alt="screen shot 2015-07-17 at 11 58 14" src="https://cloud.githubusercontent.com/assets/2538526/8745035/1d262eb8-2c7c-11e5-8811-a7ccd8a120df.png">

@gyst - may be related to #324 ?

**Comment by mattss** [comment]
Pretty sure this is just because the demo content setup creates some posts in the future.

**Comment by bfackland** [comment]
Exciting.. why would it do that?

**Comment by mattss** [comment]
No idea, but that's the most plausible explanation for what you are seeing.
