### ISSUE TITLE
Display ongoing events in sidebar

### ISSUE THREAD

**Issue by ale-rt** [ploneintranet/ploneintranet#571]
This method:
- https://github.com/ploneintranet/ploneintranet/blob/08a81f6dc31a0bfc9ece0d68a0822c478c2399d4/src/ploneintranet/workspace/browser/tiles/sidebar.py#L881

returns event:
- upcoming (start date > now)
- older (end date < now)

I think we miss:
- ongoing (start date < now and end date > now)

Without this search I am missing the event related to this sprint, that started last monday and finishes tonite :)

**Comment by pilz** [comment]
I would think it sufficient to have one section of upcoming and ongoing events. And thereby display everything where end<now under old and end>=now under upcoming. After all there is still "something" of the event upcoming.
