### ISSUE TITLE
'Older events'

### ISSUE THREAD

**Issue by cornae** [ploneintranet/ploneintranet#576]
There's a title in the sidebar that is the title of non existing content. When there are no older events, either don't display the title, or display the title and add a paragraph that says 'There no older events'. 

![image](https://cloud.githubusercontent.com/assets/738601/8746307/3f8fc3a4-2c88-11e5-8f96-5b569fa001b7.png)

**Comment by ale-rt** [comment]
Just checked this.
The current implementation is "don't display the title".

See attachment:
![image](https://cloud.githubusercontent.com/assets/1300763/8779143/09b4e18e-2f02-11e5-95b0-b817e6597ad2.png)

@cornae it is fine for you to close this one?
