### ISSUE TITLE
Quick selection mode button missing

### ISSUE THREAD

**Issue by cornae** [ploneintranet/ploneintranet#579]
![image](https://cloud.githubusercontent.com/assets/738601/8746421/4843fece-2c89-11e5-9711-855e794d9df9.png)

The button for selection mode is missing.

**Comment by gyst** [comment]
We don't have batch actions yet, do we @pilz?

**Comment by pilz** [comment]
No. But they are a big big item on my wishlist

**Comment by gyst** [comment]
Yes but it's more than just the button, it is multiple big backend stories, one for each batch function.

**Comment by pilz** [comment]
This has now been implemented
