### ISSUE TITLE
Sidebar tasks should be open when navigating to a task

### ISSUE THREAD

**Issue by adrianwhite** [ploneintranet/ploneintranet#58]
This should happen if you go directly to a task in a workspace.

**Comment by adrianwhite** [comment]
@cornae @gyst I cannot fix this in the prototype as the issue is that the initial 'current' state of the sidebar tabs and the stacks (doc listing, tasks listing etc.) is governed by pat-stacks. When initialising, pat-stacks only checks for a fragment in the url to set which is the initial visible item in the stack.

See: https://github.com/Patternslib/Patterns/blob/master/src/pat/stacks.js#L26-32

**Comment by cornae** [comment]
Yes it's, not easy at all. To be honest, I personally also don't see the need really.

**Comment by cornae** [comment]
I have an idea. The document that is the task should have the other tasks visible in the sidebar. With the module property we can control which module (tab) gets the class `.current`. Pat-stacks will then open also the right one.

**Comment by adrianwhite** [comment]
I tried that one. When initialising, stacks only uses the fragment from the url (if it exists) otherwise the first item.

**Comment by cornae** [comment]
Right. So of we switch context without injection, would that work?

> Op 14 mrt. 2015 om 20:01 heeft Adrian White notifications@github.com het volgende geschreven:
> 
> I tried that one. When initialising, stacks only uses the fragment from the url (if it exists) otherwise the first item. 
>

**Comment by adrianwhite** [comment]
I think so. 
We should solve it for a shared link too.

**Comment by jcbrand** [comment]
This issue was moved to ploneintranet/ploneintranet.prototype#13
