### ISSUE TITLE
News item points to library

### ISSUE THREAD

**Issue by cornae** [ploneintranet/ploneintranet#582]
There's a news items that points to a lib item.

![image](https://cloud.githubusercontent.com/assets/738601/8746465/dd877b8c-2c89-11e5-89cd-b3e88c0d6237.png)

This could never happen in standard PI. I think it's there because we hack this into iKath like this, but it should be in the standard product. The news items should show items from the news section and the library portlet should show items from the library section. No cross overs. 

This is probably also the reason the image is broken, because for library items a hero image is not essential.

**Comment by gyst** [comment]
I'm putting this on hold since we don't actually have a news section yet, nor do we have a library tile on the dash. Until we have those two, this is a nice bridging solution.

**Comment by pilz** [comment]
This will auto solve itself once we have a news section.
