### ISSUE TITLE
Breadcrumbs area is updated with injection

### ISSUE THREAD

**Issue by cornae** [ploneintranet/ploneintranet#583]
The breadcrumbs area is updated when you drill down in folders in workspaces. There's an ugly large spinner visible, which I should hide. It's not hidden in proto because the design didn't count on folder names there. Could the injection be removed? If that's cumbersome I can add a CSS rule to hide the spinner from the breadcrumbs area.

**Comment by pilz** [comment]
I fixed that recently.
