### ISSUE TITLE
Follow/Unfollow

### ISSUE THREAD

**Issue by cornae** [ploneintranet/ploneintranet#586]
Was there was a design change made outside the design cycle for the following pattern?

I see a different design on DEV than on proto.

DEV:

![image](https://cloud.githubusercontent.com/assets/738601/8746643/c03cbf86-2c8b-11e5-8e22-c1867ca0c4cd.png)

And the following state in proto:

![image](https://cloud.githubusercontent.com/assets/738601/8746636/b569c32e-2c8b-11e5-991c-f33e3523750e.png)

Unless there was a hard reason for a design change, please bring in sync with proto. Other wise, lets bring proto up to date with what's on dev. or they will run out of sync.

**Comment by gyst** [comment]
I guess the existing backend functionality was exposed in the UI without bringing it in conformance with proto. Dev should change, not proto.
