### ISSUE TITLE
Workflow state published not available

### ISSUE THREAD

**Issue by cornae** [ploneintranet/ploneintranet#592]
The workflow state 'published' is not available when the doc is on draft.

![image](https://cloud.githubusercontent.com/assets/738601/8747139/7e5231be-2c90-11e5-91bf-5817803e3bf9.png)

After I switch to 'pending', 'published' becomes available as an option. Published should be there already in the first place. 

![image](https://cloud.githubusercontent.com/assets/738601/8747175/a49b7ca4-2c90-11e5-901e-4189f4583744.png)

Also very oddly, the order of the states changes in the dropdown. This should remain the same. 

If it's a limitation of the back end that pending MUST be chosen by the user before published can be chosen, that would be very regrettable, because I think it's a bad UX. However, if this is the case, better display the option anyway, but disabled.

**Comment by gyst** [comment]
Yes I've seen that also - we will enable a direct transition to published.

**Comment by cornae** [comment]
Perfect!
