### ISSUE TITLE
Docs structure plone setup instance and add dependencies.

### ISSUE THREAD

**Issue by allcaps** [ploneintranet/ploneintranet#593]
The create Plone instance section can be less cluttered.

And:
"""
You will need some other tools installed for docsplit. See the docsplit installation instructions. Note that Libre Office is mentioned as optional there, but in Plone Intranet we require it.
"""

In fact I found that both Ghostscript and Libre Office are noted as "Optional" but are required. It's probably worth making it clear that explicitly clear.

**Comment by gyst** [comment]
Fixed in #595
