### ISSUE TITLE
Editing and event in a workspace does not reload the sidebar

### ISSUE THREAD

**Issue by ale-rt** [ploneintranet/ploneintranet#599]
Go here:
- http://localhost:8080/Plone/workspaces/open-market-committee/manage-information/plone-conf#document-body

I see it in the Upcoming events.

Modify the date in order to make this event past
You will not see any modification

**Comment by gyst** [comment]
NB if you are in a todo view and change its status, that triggers a refresh of the sidebar.
A similar injection can maybe be applied here for event changes.

**Comment by ale-rt** [comment]
On Fri, Jul 17, 2015 at 4:57 PM, Guido Stevens notifications@github.com
wrote:

> NB if you are in a todo view and change its status, that triggers a
> refresh of the sidebar.
> A similar injection can maybe be applied here for event changes.

Already fixed and writing tests.
But the PR requires #598 to be merged (which needs some love).

## 

Alessandro Pisa - RedTurtle Technology
E-mail: alessandro.pisa@redturtle.it
Web Site: http://www.redturtle.it
Phone: +39 0532 1915958
