### ISSUE TITLE
pat-bumper with other sides than top

### ISSUE THREAD

**Issue by cornae** [ploneintranet/ploneintranet#6]
The new pat-bumper doesn't seem to respond to other sides that the top the parent it should bump against. For the comment trails underneath documents I need it to work also when you scroll down.

**Comment by fulv** [comment]
@cornae says: 
i was thinking:

bump-side: top left right bottom

cornelis [08:52]
default = top

cornelis [08:52]
like now

cornelis [08:52]08:52
but you can combine multiple

**Comment by adrianwhite** [comment]
So if it has all four then it is always within frame?

**Comment by cornae** [comment]
Correct. Then it has no escape.

**Comment by jcbrand** [comment]
This issue was moved to ploneintranet/ploneintranet.prototype#24
