### ISSUE TITLE
Event validation start date > end date

### ISSUE THREAD

**Issue by ale-rt** [ploneintranet/ploneintranet#600]
At the moment it is allowed to create a start date greater than the end date.
This leads to the funny effect that the event is shown as a past event and a future event

**Comment by gyst** [comment]
#481 failed to add front-end validation to prevent that. Which means we have to catch this in the backend. We can either refuse to save, if we can show the error in the UI, which has my preference. If this is not easy, let's at least then rewrite the end date to start+1hour so our backend is consistent. @ale-rt do you agree?

**Comment by ale-rt** [comment]
+1

**Comment by pilz** [comment]
Careful. Afaik we don't have a concept in showing backend errors properly in the frontend at the moment - but in a portal_statusmessage. This is not really nice. So before investing more than trivial time into this, the proposed approach in #481 using validation.js could be considered instead.

**Comment by gyst** [comment]
Workaround: if end < start: force end to start + 1hour. Can be done in backend without requiring any UI change.

**Comment by pilz** [comment]
+1

**Comment by pilz** [comment]
JC has done a pattern for validate.js which is able to do this. We "just" need to integrate it now and use it instead of the parsley one.

**Comment by ale-rt** [comment]
I am checking pat-validate but it does not seem to be easy to have an invariant validator like the one we need here.

We need to check  4 inputs:
1. a start input type=date
2. a start input type=time
3. an end input type=date
4. an end input type=time

the logic is:
if 1<3 -> ok
elif 1>3 -> ok
elif 1=3 and 2<4 ok
else ko

Any hints?

**Comment by jcbrand** [comment]
@ale-rt pat-validate is old and based on Parsley which doesn't work well with the patterns approach. I created a new pattern pat-validation which does validation between dates. We're not using it in ploneintranet yet, but Syslab is already using it in another project. The idea being to start using it in PI as well.

Eventually we want to deprecate and remove pat-validate.

**Comment by ale-rt** [comment]
Ah ok! I did not understand correctly previous comments!
To close this story I am implementing the workaround suggested in https://github.com/ploneintranet/ploneintranet/issues/600#issuecomment-122847127

**Comment by ale-rt** [comment]
#668 and #671 should close this activity.

In case of any objection please merge at least #676, which modifies injection to make the status messages appear on the page after saving.

**Comment by gyst** [comment]
#668 and #676 are merged, #671 ready to merge.
