### ISSUE TITLE
Show context of a post?

### ISSUE THREAD

**Issue by pilz** [ploneintranet/ploneintranet#618]
When looking at the dashboard, I see posts from all locations. Taken out of the context of a workspace, a post may look funny. Would it be interesting/feasible to show the context of a post on the dashboard? 
E.g. "posted in Open Market Committee 9:23"

![context](https://cloud.githubusercontent.com/assets/122351/8802547/90d99c0c-2fc2-11e5-926f-23efe8ea0e9a.png)

**Comment by gyst** [comment]
On 21/07/15 11:18, Alexander Pilz wrote:

> When looking at the dashboard, I see posts from all locations. Taken out
> of the context of a workspace, a post may look funny. Would it be
> interesting/feasible to show the context of a post on the dashboard?
> E.g. "posted in Open Market Committee 9:23"

Is already in prototype. Trivial to implement in dev and a necessary
part of content updates.
https://github.com/ploneintranet/ploneintranet/issues/359

## 

```
Guido Stevens  |  +31.43.3618933  |  http://cosent.nl

s o c i a l   k n o w l e d g e   t e c h n o l o g y
```

**Comment by gyst** [comment]
On 21/07/15 11:18, Alexander Pilz wrote:

> When looking at the dashboard, I see posts from all locations. Taken out

https://github.com/ploneintranet/ploneintranet/issues/620

## 

```
Guido Stevens  |  +31.43.3618933  |  http://cosent.nl

s o c i a l   k n o w l e d g e   t e c h n o l o g y
```

**Comment by gyst** [comment]
Oops I opened a duplicate. Will close #620
