### ISSUE TITLE
Post editing: cancel button does not work correct

### ISSUE THREAD

**Issue by angeldasangel** [ploneintranet/ploneintranet#622]
When I add a user or a tag to a new post and then click the button "cancel" the @-statement for the user and the hashtag for the tag are not removed. Also the text is not reset, but this can be done manually.
There is no possibility to remove statements for user or tag.

In the select user or select tag popup:
Unchecking the checkbox belonging to the user or tag leads to display the loading icon inside the post box and the popup and leaves the post in an uneditable state.

**Comment by ale-rt** [comment]
I think this is a problem in pat-content-mirror.
There are registration for propertychange and input:
- https://github.com/ploneintranet/pat-content-mirror/blob/5f0e9362849a38e098da36c6f5b440419d2e5b2f/src/pat-content-mirror.js#L25

Probably the same event should be fired for change (like it is in the case of text areas).

Will investigate a bit more.

**Comment by ale-rt** [comment]
See: ploneintranet/pat-content-mirror/issues/4

**Comment by garbas** [comment]
[fixed](https://github.com/ploneintranet/pat-content-mirror/commit/181a55591db14d73dafaa17bf910f6cd229baea2)

**Comment by ale-rt** [comment]
Thanks!
