### ISSUE TITLE
Upgrade to Plone 5.0b3

### ISSUE THREAD

**Issue by pbauer** [ploneintranet/ploneintranet#635]

**Comment by pbauer** [comment]
I alreay started working on that.

**Comment by pilz** [comment]
beautiful! Can't wait…!!!

**Comment by ale-rt** [comment]
Great!

**Comment by pbauer** [comment]
That was pretty easy. Please review #640 and https://github.com/collective/collective.externaleditor/pull/3
Only collective.externaleditor gave me some headaches.

**Comment by pilz** [comment]
merged

**Comment by ale-rt** [comment]
I am closing this one
