### ISSUE TITLE
Notifications: Duplicate entries when mentioning

### ISSUE THREAD

**Issue by pilz** [ploneintranet/ploneintranet#644]
![bildschirmfoto 2015-07-31 um 11 25 27](https://cloud.githubusercontent.com/assets/138906/9004519/f8be0928-3776-11e5-88af-7047e64b9b26.png)

When posting in a workspace, the mentioned user get's two notifications, one with the local hostname (not the vhm original site name), without title or profile image and a second one with all fields set correctly.

**Comment by ale-rt** [comment]
@pilz there was a bad bug causing duplicate post creation, fixed in #662

Would you mind to confirm that #662 closes this one also?

**Comment by pilz** [comment]
Yes, this is also fixed. Thanks!
