### ISSUE TITLE
Activity Stream: comments on existing posts

### ISSUE THREAD

**Issue by angeldasangel** [ploneintranet/ploneintranet#645]
When writing a post and then writing a comment  with the same user logged in before reloading the page, some errors occur:
- on the dashboard and in the user profile for each comment a post is displayed (the original post but without comments)
- in the workspace the comments are missing

also all comments are shown twice.

**Comment by pysailor** [comment]
Also, when users are mentioned inside a comment, mutliple ConflictErrors occur, preventing the comment from being saved.

**Comment by ale-rt** [comment]
I fixed the original issue, checking if it fixes also @pysailor note

**Comment by ale-rt** [comment]
It seems this is also fixing the conflict error, @pysailor I would be glad if you can double check, thanks!

**Comment by pysailor** [comment]
One small line of code removed, 2 bugs fixed :-)
