### ISSUE TITLE
solr PR builder

### ISSUE THREAD

**Issue by gyst** [ploneintranet/ploneintranet#691]

**Comment by mattss** [comment]
Unfortunately, Jenkins-github integration is limited if you have multiple PR checkers. It seems that the first check that completes will update the PR with 'everything's fine', even if the other one is still running.

The alternative approaches I see therefore are:
1. We continue to run the solr search tests manually on master pushes (simplest, but with obvious downsides)
2. We update the existing PR job to run the solr build and solr-search tests _as well_, after the main tests. This is the next simplest (adding a few lines to jenkins configs) but will require jenkins to build out multiple times and considerably lengthen the test times.
3. We ditch the zcatalog-based search, make solr a requirement and run all tests with the solr config every time. This is the most complicated, as it involves merging the buildouts and possibly adding supervisor, and updating all the relevant documentation.

Personally I would vote for 1 or 2 now (in the interest of getting venus out), and then look into 3 for the next release.

Any thoughts?

**Comment by pilz** [comment]
I fully agree. 
I would even say that as long solr is not fully integrated as the default, it is also not the priority and we should do 1.
Once we integrate solr via super isor as default, it superceeds zcatalog as the default and we do 3. after venus. 

Alexander Pilz (mobil)

**Comment by pysailor** [comment]
I would also favor 1 or 2 for now. Considering that the tests for PRs already take a long time to complete, I opt for 1.

**Comment by gyst** [comment]
On 21/08/15 11:33, Matthew Sital-Singh wrote:

> Unfortunately, Jenkins-github integration is limited if you have
> multiple PR checkers. It seems that the first check that completes will
> update the PR with 'everything's fine', even if the other one is still
> running.
> 
> The alternative approaches I see therefore are:
> 1. We continue to run the solr search tests manually on master pushes
>    (simplest, but with obvious downsides)
> 2. We update the existing PR job to run the solr build and solr-search
>    tests /as well/, after the main tests. This is the next simplest
>    (adding a few lines to jenkins configs) but will require jenkins to
>    build out multiple times and considerably lengthen the test times.
> 3. We ditch the zcatalog-based search, make solr a requirement and run
>    all tests with the solr config every time. This is the most
>    complicated, as it involves merging the buildouts and possibly
>    adding supervisor, and updating all the relevant documentation.
> 
> Personally I would vote for 1 or 2 now (in the interest of getting venus
> out), and then look into 3 for the next release.
1. We update the existing PR job to /only/ run with solr.

Developers can use fast zcatalog based test builds for any functionality
that does not require solr. But all pulls will be tested on our full
default stack which is solr not zcatalog.

Best of both worlds:
- dev workflow unchanged
- jenkins stays fast
- all solr regressions are caught

Only downside:
- zcatalog-only regressions (that are not in solr) are not caught by
  jenkins. Duh.

## 

```
Guido Stevens  |  +31.43.3618933  |  http://cosent.nl

s o c i a l   k n o w l e d g e   t e c h n o l o g y
```

**Comment by mattss** [comment]
I'm happy to give @gyst 's suggestion a go unless anyone has any issues with it.

**Comment by pilz** [comment]
Sounds good

> Am 21.08.2015 um 12:37 schrieb Matthew Sital-Singh notifications@github.com:
> 
> I'm happy to give @gyst https://github.com/gyst 's suggestion a go unless anyone has any issues with it.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/ploneintranet/ploneintranet/issues/691#issuecomment-133370004.

## 

Alexander Pilz
SYSLAB.COM GmbH, Landwehrstrasse 60-62, 80336 Munich, Germany
Tel: +49 89 3063589-0 - Fax: +49 89 3063589-9
http://www.syslab.com - Amtsgericht Muenchen, HRB 135057
Steuernummer 143/184/50154 - Ust.-ID: DE212842815

**Comment by mattss** [comment]
Jenkins now running all tests using solr build in PR https://github.com/ploneintranet/ploneintranet/pull/711
