### ISSUE TITLE
finish async / doc conversion refactoring

### ISSUE THREAD

**Issue by gyst** [ploneintranet/ploneintranet#693]

**Comment by mattss** [comment]
A quick primer on the state of async in preparation for tomorrow.

Current state is in the async-final branch:
https://github.com/ploneintranet/ploneintranet/tree/async-final

@wengole wrote up the overall plan in some detail in the 'async' docs as part of the branch - that is worth a read: https://github.com/ploneintranet/ploneintranet/blob/async-final/docs/development/components/async.rst

In summary, this branch tries to do three things:
a) Establish a celery setup where browser views can be put in a queue, for celery to trigger later (as the same user - using the cookie for auth).
b) Consolidate the mishmash of docconv-related packages (pi.docconv.client, slc.docconv, coll.documentviewer) into pi.async.
c) Add support for b) via a)

Unfortunately, in the process of doing part b), some of the infrastructure needed for c) was lost - specifically the code around storing attachments/previews on status updates. Additionally it proved tricky to work out how to provide unique browser views for status attachments that celery could call to initiate conversion on them.

Possible approaches to resolving this:

1) Try and merge master into this branch and continue where we left off, being careful not to lose any other changes made recently in the docconv eggs that have been ripped out of this branch. As this branch is very stale, this may be a challenge.
2) Try and extract the celery architecture from this branch into a new branch, and leave the existing doc-conv stack as is, but plugging it into celery.

Either way, we probably need to establish a consistent way to trigger and store conversion both for real documents and for status updates.

/cc @gyst @pilz @wengole

**Comment by pilz** [comment]
This has been done in PRs #762 and #765. I propose to follow up there.
