### ISSUE TITLE
library page preview breaks search result preview rendering

### ISSUE THREAD

**Issue by gyst** [ploneintranet/ploneintranet#727]
If you add a leadimage to a Document contained in the library (via Barceloneta), if you then search for that page the SRP links to a 404 on (page url)/docconv_image_thumb.jpg

ikath #12253

**Comment by gyst** [comment]
@pilz Below my analysis. I don't know how to move forward.

The thumbs URL is shown because the brain `has_thumbs`
https://github.com/ploneintranet/ploneintranet/blob/master/src/ploneintranet/search/base.py#L91
because the indexer for `has_thumbs` sees that the object is docconv enabled
https://github.com/ploneintranet/ploneintranet/blob/master/src/ploneintranet/docconv/client/indexers.py#L12

There's no issue with browserlayers or whatever. The document conversion kicks in, but then bails because there's no virtual_url_parts
https://github.com/ploneintranet/ploneintranet/blob/master/src/ploneintranet/docconv/client/fetcher.py#L400

This only happens when a Document is added. When a document is modified preview updating is disabled.
https://github.com/ploneintranet/ploneintranet/blob/master/src/ploneintranet/docconv/client/handlers.py#L52
That's very recent of course. 8545ca76 (Wolfgang Thomas  2015-08-21

So:
- the REQUEST check should also check for leadimage change
- which only makes sense if the virtual_url_parts abort is not triggered

**Comment by pilz** [comment]
You got the wrong indexer. Library has its own indexer for library items:
https://github.com/ploneintranet/ploneintranet/blob/master/src/ploneintranet/library/indexers.py#L21
It says true if there is a preview image. 

The issue therefore is more in the searchresults, which looks for "has_thumbs" and assumes docconv preview images and only shows images for "Images".
https://github.com/ploneintranet/ploneintranet/blob/master/src/ploneintranet/search/base.py#L91

We can here make the differentiation more precise to fix this quickly. 
See #729
However this is mixing concepts and search is using the "has_thumb" with the slightly different assumption that it always refers to docconv previews. We may want to - while refactoring docconv - find a generic way (api?) to get the preview images for any content type.

**Comment by gyst** [comment]
On 26/08/15 22:20, Alexander Pilz wrote:

> You got the wrong indexer. Library has its own indexer for library items:
> https://github.com/ploneintranet/ploneintranet/blob/master/src/ploneintranet/library/indexers.py#L21
> It says true if there is a preview image.

Note that these library indexers present a race condition with the
docconv indexer for all NewsItem and Document content, also in
workspaces. There's no deterministic preference between IContentish and
IDocument.

## 

```
Guido Stevens  |  +31.43.3618933  |  http://cosent.nl

s o c i a l   k n o w l e d g e   t e c h n o l o g y
```
