### ISSUE TITLE
jenkins is unstable

### ISSUE THREAD

**Issue by gyst** [ploneintranet/ploneintranet#731]
When triggering pull request builds I frequently get broken builds:
./bootstrap_jenkins.sh: line 16: ./bin/buildout: No such file or directory

The builds that do run then frequently hang at the start of the robot testing

in 19.122 seconds.
  Set up plone.app.robotframework.remote.AutoLoginRemoteLibrary:RobotRemote in 0.013 seconds.
  Set up ploneintranet.suite.testing.PLONEINTRANET_SUITE_ROBOT in 0.000 seconds.
  Running:
.The following test left new threads behind:
Page contains just one meta for viewport (test_transforms.robot)
New thread(s): [<_DummyThread(Dummy-23, started daemon 140714358474496)>]

(loading icon keeps circling for ages)

After a while these are then disappear, then re-appear, in the Jenkins console (as if they're auto-restarted by Jenkins) but the console output remains hanging, though some come through in the end and mark a PR green.

PR ended up green: 
https://github.com/ploneintranet/ploneintranet/pull/729

PRs that keep hanging in orange:
https://github.com/ploneintranet/ploneintranet/pull/683
https://github.com/ploneintranet/ploneintranet/pull/681
https://github.com/ploneintranet/ploneintranet/pull/671

This sad state of affairs obviously makes it nigh impossible to clear out the PR backlog and get code into master. @mattss I hope you can find a solution.

**Comment by gyst** [comment]
Additionally, we now have the master builds failing for reasons that are independent of code changes on merges that were pre-tested green on the PR builder.

http://jenkins.ploneintranet.net/job/complete.Ploneintranet.master.False/414/
http://jenkins.ploneintranet.net/job/complete.Ploneintranet.master.False/415/

415 for example was a no-op change versus 414 - only documentation update.

**Comment by mattss** [comment]
@gyst can you get the master build to pass locally?

**Comment by gyst** [comment]
On 27/08/15 14:28, Matthew Sital-Singh wrote:

> @gyst https://github.com/gyst can you get the master build to pass
> locally?

Will run that now.

## 

```
Guido Stevens  |  +31.43.3618933  |  http://cosent.nl

s o c i a l   k n o w l e d g e   t e c h n o l o g y
```

**Comment by mattss** [comment]
I _think_ this may be because the pull request builder will often run multiple builds at once, in the same workspace.

The simple fix would be to make sure it only runs one at a time, which would obviously reeaally slow things down during a sprint.

An alternative solution is beyond my jenkins knowledge at this point. There seem to be some options regarding using docker containers to isolate builds (docker _is_ the answer to everything it seems), but that is probably a challenge to get right.

**Comment by pilz** [comment]
We could also investigate on running jenkins slaves on other machines…

> Am 28.08.2015 um 11:49 schrieb Matthew Sital-Singh notifications@github.com:
> 
> I think this may be because the pull request builder will often run multiple builds at once, in the same workspace.
> 
> The simple fix would be to make sure it only runs one at a time, which would obviously reeaally slow things down during a sprint.
> 
> An alternative solution is beyond my jenkins knowledge at this point. There seem to be some options regarding using docker containers to isolate builds (docker is the answer to everything it seems), but that is probably a challenge to get right.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/ploneintranet/ploneintranet/issues/731#issuecomment-135722735.

## 

Alexander Pilz
SYSLAB.COM GmbH, Landwehrstrasse 60-62, 80336 Munich, Germany
Tel: +49 89 3063589-0 - Fax: +49 89 3063589-9
http://www.syslab.com - Amtsgericht Muenchen, HRB 135057
Steuernummer 143/184/50154 - Ust.-ID: DE212842815

**Comment by gyst** [comment]
On 28/08/15 11:49, Matthew Sital-Singh wrote:

> I /think/ this may be because the pull request builder will often run
> multiple builds at once, in the same workspace.

I can't imagine how that can be valid.

> The simple fix would be to make sure it only runs one at a time, which
> would obviously reeaally slow things down during a sprint.

Not for actual pull requests, only if you use it instead of local
testing, which we all do but can be worked around.

A build takes what, 10 minutes? We don't get much actual pull requests
to actually saturate a worker.

If we're sprinting it's a matter of running two ploneintranet builds
locally, one for development one for testing, synced via branch
push/pulls, and only opening a real pull request once the tests are OK.

## :*CU#

```
Guido Stevens  |  +31.43.3618933  |  http://cosent.nl

s o c i a l   k n o w l e d g e   t e c h n o l o g y
```

**Comment by gyst** [comment]
On 28/08/15 11:54, Alexander Pilz wrote:

> We could also investigate on running jenkins slaves on other machines…

+1

## 

```
Guido Stevens  |  +31.43.3618933  |  http://cosent.nl

s o c i a l   k n o w l e d g e   t e c h n o l o g y
```

**Comment by pilz** [comment]
> Am 28.08.2015 um 11:55 schrieb Guido Stevens notifications@github.com:
> 
> On 28/08/15 11:49, Matthew Sital-Singh wrote:
> 
> > I /think/ this may be because the pull request builder will often run
> > multiple builds at once, in the same workspace.
> 
> I can't imagine how that can be valid.

If one build starts, then the other closely after, the second might conflict and when that happens during bootstrapping, no bin/buildout script is created. Seen that before.

> > The simple fix would be to make sure it only runs one at a time, which
> > would obviously reeaally slow things down during a sprint.
> 
> Not for actual pull requests, only if you use it instead of local
> testing, which we all do but can be worked around.
> 
> A build takes what, 10 minutes? We don't get much actual pull requests
> to actually saturate a worker.

26 Mins nowadays…

> If we're sprinting it's a matter of running two ploneintranet builds
> locally, one for development one for testing, synced via branch
> push/pulls, and only opening a real pull request once the tests are OK.

When you are chasing Heisenbugs - which appeared often in the recent past, you often have more than 2 branches in the making.

> ## :*CU#
> 
> Guido Stevens | +31.43.3618933 | http://cosent.nl
> 
> s o c i a l k n o w l e d g e t e c h n o l o g y
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/ploneintranet/ploneintranet/issues/731#issuecomment-135723594.

## 

Alexander Pilz
SYSLAB.COM GmbH, Landwehrstrasse 60-62, 80336 Munich, Germany
Tel: +49 89 3063589-0 - Fax: +49 89 3063589-9
http://www.syslab.com - Amtsgericht Muenchen, HRB 135057
Steuernummer 143/184/50154 - Ust.-ID: DE212842815

**Comment by pilz** [comment]
We have added 2 more slaves. Don't know if you think this is enough to close this ticket?

**Comment by gyst** [comment]
It certainly helps. But given that we're now pushing towards a release, and looking at the Jenkins build queue, we could use a few extra slaves until after ploneconf. Of course I don't know if that's feasible at all in terms of deployment capacity.

**Comment by gyst** [comment]
Actually we still have race conditions between builds, even on separate machines.

Caused by: hudson.plugins.git.GitLockFailedException: Could not lock repository. Please try again

This was as part of a no-op build (no code changes).
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/871/
PR: https://github.com/ploneintranet/ploneintranet/pull/768

**Comment by gyst** [comment]
More mess, on https://github.com/ploneintranet/ploneintranet/pull/762:

stderr: error: Ref refs/remotes/origin/pr/762/head is at 061c51cb25098f42d699c391e8f9f7aa11f15b30 but expected 9df0ead9ebd7efe898024d297f93e224a94d2232

http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/868/console

**Comment by gyst** [comment]
I may have found a possible source of this in bootstrap_jenkins.sh which does multiple invocations of  `virtualenv --relocatable .`. As the docs say::

The --relocatable option currently has a number of issues, and is not guaranteed to work in all circumstances. It is possible that the option will be deprecated in a future version of virtualenv.

Also: If you use this flag to create an environment, currently, the --system-site-packages option will be implied.

Both are suggestive of the kind of environment leagage problems we've seen.

Instead of using `--relocatable` an alternative workaround for shebang path limits is discussed here:
http://stackoverflow.com/questions/10813538/shebang-line-limit-in-bash-and-linux-kernel

**Comment by mattss** [comment]
The relocatable stuff was added before my time. It's not something I've used with jenkins before. Anyone know if we actually need it?

**Comment by gyst** [comment]
On 30/09/15 11:16, Matthew Sital-Singh wrote:

> The relocatable stuff was added before my time. It's not something I've
> used with jenkins before. Anyone know if we actually need it?

The comment in the code says it's needed to avoid exceeding the 127-char
shebang limit - we have deep dir structures on Jenkins apparently - but
I haven't checked whether that is actually a problem.

That's why I posted a link to other solutions to the shebang limit. Like
recompiling the Linux kernel with a bigger limit :-).

## :*CU#

```
Guido Stevens  |  +31.43.3618933  |  http://cosent.nl

s o c i a l   k n o w l e d g e   t e c h n o l o g y
```

**Comment by gyst** [comment]
Another data point: this error in build 968 definitely points to leakage from build 969 which was running at the same time - but on a different machine!!! - 968 ran on ext6 and 969 ran on ext8.

The below error can only be explained as:
- we're on branch 49_buildout.d
- trying to parse ploneintranet/async/browser/configure.zcml leaked in somehow from branch async-docs (which is the only branch where GeneratePreviewsView lives)
- but the 49_buildout.d views.py module does not have that view

Given that this cross-build pollution occurs across separate virtuals this points to a problem with the pull request builder.

ZopeXMLConfigurationError: File "/var/lib/jenkins/workspace/Plone.Intranet.Pull.Request.Builder/src/ploneintranet/async/configure.zcml", line 10.2-10.32
    ZopeXMLConfigurationError: File "/var/lib/jenkins/workspace/Plone.Intranet.Pull.Request.Builder/src/ploneintranet/async/browser/configure.zcml", line 36.2-42.8
    ConfigurationError: ('Invalid value for', 'class', 'ImportError: Module ploneintranet.async.browser.views has no global GeneratePreviewsView')

**Comment by pilz** [comment]
The only way how I can think this is possible would be if the master is actually doing the checkout locally and pushes it to the slave. If it at the same time - in the same dir - runs also another PR, this will fail.

> Am 01.10.2015 um 09:48 schrieb Guido Stevens notifications@github.com:
> 
> Another data point: this error in build 968 definitely points to leakage from build 969 which was running at the same time - but on a different machine!!! - 968 ran on ext6 and 969 ran on ext8.
> 
> The below error can only be explained as:
> 
> we're on branch 49_buildout.d
> trying to parse ploneintranet/async/browser/configure.zcml leaked in somehow from branch async-docs (which is the only branch where GeneratePreviewsView lives)
> but the 49_buildout.d views.py module does not have that view
> Given that this cross-build pollution occurs across separate virtuals this points to a problem with the pull request builder.
> 
> ZopeXMLConfigurationError: File "/var/lib/jenkins/workspace/Plone.Intranet.Pull.Request.Builder/src/ploneintranet/async/configure.zcml", line 10.2-10.32
> ZopeXMLConfigurationError: File "/var/lib/jenkins/workspace/Plone.Intranet.Pull.Request.Builder/src/ploneintranet/async/browser/configure.zcml", line 36.2-42.8
> ConfigurationError: ('Invalid value for', 'class', 'ImportError: Module ploneintranet.async.browser.views has no global GeneratePreviewsView')
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/ploneintranet/ploneintranet/issues/731#issuecomment-144645930.

## 

Alexander Pilz
SYSLAB.COM GmbH, Landwehrstrasse 60-62, 80336 Munich, Germany
Tel: +49 89 3063589-0 - Fax: +49 89 3063589-9
http://www.syslab.com - Amtsgericht Muenchen, HRB 135057
Steuernummer 143/184/50154 - Ust.-ID: DE212842815

**Comment by pilz** [comment]
fwiw I am so scared from this that I now took the slaves out of rotation. I think a slow stable master is much better than slightly quicker confusion. Let's see if that helps.

**Comment by ale-rt** [comment]
Now it seems that jenkins is stuck.
Is there any chance to give him a reset?

**Comment by pilz** [comment]
I restarted jenkins. Seems to get stuck every 3 months ?!?
Let's see if it recovers.

**Comment by ale-rt** [comment]
Thanks! :)

**Comment by mattss** [comment]
@pilz Would love to move forward with jenkins/travis so it doesn't hold up development / PR review. @wengole is up for trying to resolve this, or perhaps switching us back to travis if necessary. Can he work with anyone at syslab on this next week? @pysailor are you game?

**Comment by pilz** [comment]
We should be around, but working towards a deadline next wednesday evening. So it might be a bit hectic. I'd also love to remove that hurdle very soon and will look in a bit more this weekend.

**Comment by pilz** [comment]
Not unstable anymore, besides the usual hickup, but generally under control
