### ISSUE TITLE
Deletion of a File with Umlaut in the Filename gives UnicodeDecodeError

### ISSUE THREAD

**Issue by pilz** [ploneintranet/ploneintranet#734]
Module z3c.form.button, line 170, in **call**
Module plone.app.content.browser.actions, line 63, in handle_delete
Module Products.statusmessages.adapter, line 34, in add
Module zope.i18n, line 126, in translate
Module zope.i18n.translationdomain, line 78, in translate
Module zope.i18n.translationdomain, line 140, in _recursive_translate
Module zope.i18n, line 164, in interpolate
Module zope.i18n, line 159, in replace
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5: ordinal not in range(128)
- Upload a pdf with the name "Geschäfte.pdf" to a workspace
- open it
- click the trashcan
- Confirm the delete
  Traceback above

Also the delete confirmation is different than the ones recently fixed for events and documents, perhaps that is connected.

**Comment by cillianderoiste** [comment]
Fixed by #736
