### ISSUE TITLE
Update/Specify versions for supported releases

### ISSUE THREAD

**Issue by svx** [ploneintranet/ploneintranet#764]
Clarify version of Ubuntu and Ruby.

On: http://docs.ploneintranet.org/installation/mercury.html is 'only' mentioned Ubuntu and Ruby, but not which versions of both. 

Ubuntu for 12.04 for example comes out of the box with another version of Ruby than Ubuntu 14.04, does it work on both versions ?

Ubuntu 12.04 is official supported till 2017.

**Comment by gyst** [comment]
Mercury is outdated by now, but I'll make sure to fix this documentation for the upcoming 1.0 Venus release.
