### ISSUE TITLE
Remove source dependencies

### ISSUE THREAD

**Issue by gyst** [ploneintranet/ploneintranet#786]
We need to remove any source checkouts before we can do a proper Venus release.
[x] collective.documentviewer https://github.com/collective/collective.documentviewer/issues/53
[x] slc.docconv
[x] collective.celery

**Comment by pilz** [comment]
> Am 23.09.2015 um 12:34 schrieb Guido Stevens notifications@github.com:
> 
> We need to remove any source checkouts before we can do a proper Venus release.
> [ ] collective.documentviewer
> 
> We need a fix that is only in master. If you ping Nathan, I am sure he’d cut a quick 4.0.1 release
> 
> [ ] slc.docconv
> 
> That should not be necessary anymore after you merged the docconv refactoring
> [ ] collective.celery collective/collective.documentviewer#53 https://github.com/collective/collective.documentviewer/issues/53
> 
> No idea about that
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/ploneintranet/ploneintranet/issues/786.

## 

Alexander Pilz
SYSLAB.COM GmbH, Landwehrstrasse 60-62, 80336 Munich, Germany
Tel: +49 89 3063589-0 - Fax: +49 89 3063589-9
http://www.syslab.com - Amtsgericht Muenchen, HRB 135057
Steuernummer 143/184/50154 - Ust.-ID: DE212842815

**Comment by gyst** [comment]
Yes I filed a ticket for Nathan.
I'll try and remove the other dependencies, see what the tests say.
