### ISSUE TITLE
Solr site isolation

### ISSUE THREAD

**Issue by gyst** [ploneintranet/ploneintranet#804]
The solr index is not segmented by site. As a result, if you run multiple Plone Intranet sites against the same Solr instance, all documents in all these sites get indexed into the same Solr. The current search implementation searches all of Solr and returns matches from all found documents, regardless of the Plone site in which they're located.

The only difference between Plone sites for indexed documents, is the start of the `path_string` index. This is used by `collective.solr` to provide site isolation: by injecting a path query anchored on the SiteRoot by default. I would suggest to only inject such a default path into the query, if no path filter is already defined on the query; that way developers can implement federated (cross-site) search if they want to, while the default implementation provides site isolation by default.

Since we're not planning on deploying multihosted Plone Intranet this is not a big issue. But it may result in weird bugs in development and/or evaluation setups.

To reproduce:
- ZMI create a Plone site 'Plone', import GS profile 'Plone Intranet Suite: Create Testing Content'
- ZMI create a Plone site 'Plone2', import GS profile 'Plone Intranet Suite' (default without testing content)
- As Zope admin, go to http://localhost:8080/Plone2/search and search for `min`. You will find results from the other Plone site.

For unittesting I guess it would be sufficient to inject a fake document into the solr index with a path outside the normal Plone site.

**Comment by pilz** [comment]
Fixed in master for 1.3

**Comment by gyst** [comment]
Fixed in 102722246561a87918a380125c3bb32d0a1de09a

**Comment by gyst** [comment]
refs quaive/ploneintranet#1284
