### ISSUE TITLE
Support for analytics code

### ISSUE THREAD

**Issue by mattss** [ploneintranet/ploneintranet#819]
Plone supports an analytics code snippet, but I don't think that we currently support this in Plone Intranet. A simple win would be to update the diazo rules to bring it across from Plone.

@gyst Any thoughts on the priority of this? It's a pretty important feature for websites, but not so much for private intranets possibly.

**Comment by gyst** [comment]
On 06-10-15 12:19, Matthew Sital-Singh wrote:

> Plone supports an analytics code snippet, but I don't think that we
> currently support this in Plone Intranet. A simple win would be to
> update the diazo rules to bring it across from Plone.

+1

> @gyst Any thoughts on the priority of this? It's a pretty important
> feature for websites, but not so much for private intranets
> possibly.

Doing this with Piwik makes more sense than pluggin in a security leak
with Google Analytics.

Beyond that I'd like to develop a true analytics console that builds
upon the event logging system we're putting in place to "natively" build
an overview of what's going on. Later :-)

## 

```
Guido Stevens  |  +31.43.3618933  |  http://cosent.nl

s o c i a l   k n o w l e d g e   t e c h n o l o g y
```

**Comment by gyst** [comment]
+1 for simply supporting the existing Plone snippet in Diazo.
