### ISSUE TITLE
WS: disable link on special role for users with only view permission 

### ISSUE THREAD

**Issue by angeldasangel** [ploneintranet/ploneintranet#828]
In a Workspace on tab settings -> user:
If logged in as a user with only view permissions, you see the list of users and the link on the orange role-name beneath the user (e.g. "lesen" in screenshot) the submenu does not open to change the role (as it does when you have the permission to edit the users) but the spinning wheel is displayed and nothing happens.

Also when I try to open the link in a new tab, the url it points to is not found.

Please remove or disable the link for users without the necessary permissions.

![screen shot 2015-09-30 at 11 00 27](https://cloud.githubusercontent.com/assets/2470824/10391628/73354eb0-6e80-11e5-9e9e-ce9a6c88fb3a.png)

**Comment by gyst** [comment]
Cannot reproduce. I already fixed this in adf5c2eae9c2bbe60 2 weeks ago. The injection in this scenario will load the profile page of that user (instead of the role manipulation popup). Given that the screenshot is from iKath I guess that fix needs porting to iKath. /cc @pilz
