### ISSUE TITLE
 button "open in external editor" should be displayed only for users with edit permission

### ISSUE THREAD

**Issue by angeldasangel** [ploneintranet/ploneintranet#829]
If a user has no edit persmissions on a file, the external edit button (if available) is still displayed and leads to a permission error.

Please hide the button if the user has no permission to edit the file.

**Comment by gyst** [comment]
I don't think the external editor is even activated in a vanilla OOTB ploneintranet install. Is this an iKath issue? /cc @pilz . Cannot reproduce, closing, feel free to reopen with a test scenario that reproduces this.
