### ISSUE TITLE
Remove workflow from event

### ISSUE THREAD

**Issue by pilz** [ploneintranet/ploneintranet#831]
I guess the event is something that all people in a workflow should be able to see and the danger is more that creators forget to get it published, so I guess we might want to remove the workflow from events and have it inherit its permissions from the workspace?

**Comment by gyst** [comment]
+1. Very similar to #559

**Comment by gyst** [comment]
NB this should only be applied within the workspace content workflow not globally.

**Comment by pilz** [comment]
fixed upstream
