### ISSUE TITLE
The 'mention' and 'tag' search boxes are hidden in social comment in certain scroll positions

### ISSUE THREAD

**Issue by bfackland** [ploneintranet/ploneintranet#849]
User has to manually scroll to reveal popup, which isn't user-friendly.

![screen shot 2015-10-22 at 11 20 30](https://cloud.githubusercontent.com/assets/2538526/10662875/343300d4-78af-11e5-85f0-6bc17cee8b41.png)

**Comment by mattss** [comment]
Moved to the prototype repo: https://github.com/quaive/ploneintranet.prototype/issues/188
