### ISSUE TITLE
Confusing ‘stemming’ of spelling suggestions (e.g. ntsight -> netsigh -- no “t” at the end)

### ISSUE THREAD

**Issue by bfackland** [ploneintranet/ploneintranet#852]
It's almost like the suggestion always misses the last character.

![screen shot 2015-10-22 at 11 58 42](https://cloud.githubusercontent.com/assets/2538526/10663562/427c90ba-78b4-11e5-8f17-f0db19b446f9.png)

**Comment by pilz** [comment]
I am having several netsighs every day ;)

**Comment by bfackland** [comment]
;)

**Comment by mattss** [comment]
When you say 'always', do you  mean that you are seeing it with every word you try?

**Comment by bfackland** [comment]
It seems to occur consistently, regardless of the term entered. E.g. "nwsletter" has the suggestion "newslette" (without the "r").

It almost seems like the suggestion is truncated every time.

**Comment by mgrbyte** [comment]
[This](http://stackoverflow.com/questions/12697897/solr-facet-search-truncate-words) seems to be a good description of what's happening
