### ISSUE TITLE
Today's comments on a social post are not ordered correctly 

### ISSUE THREAD

**Issue by bfackland** [ploneintranet/ploneintranet#853]
If you leave a comment today, it moves to the top of the comments. The remainder are in chronological order.

If you make two comments today, you get:
- first comment today
- second comment today
- oldest comment
- ..remaining comments in chronological order..

![screen shot 2015-10-22 at 12 01 39](https://cloud.githubusercontent.com/assets/2538526/10663638/d1c92b70-78b4-11e5-909c-7f9532f7e639.png)

**Comment by mattss** [comment]
Can you clarify how you think this should work?

a) new comments are added to the top of a reverse-date-ordered stream
b) new comments are added to the bottom of a date-ordered stream (potentially off screen)

**Comment by bfackland** [comment]
I would say that I expect to write a comment below the most recent comment - so I think they should always be chronological. However, now that you raise the point, one might prefer to see the most recent comment directly under the original post, rather than doing lots of scrolling. I imagine one solution to this would be to only ever show the most recent three comments, with some kind of 'reveal' option for any that are older.

What is the 'industry standard' way of doing this?

**Comment by mattss** [comment]
Facebook does a similar thing to what you are suggesting:
- Chronological display of the most recent 'x' posts
- Option to 'show previous comments'

**Comment by bfackland** [comment]
So maybe for now we should just show _all_ comments chronologically. In due course, discuss UI refinement that can hides a portion to improve user experience.

> On 22 Oct 2015, at 15:37, Matthew Sital-Singh notifications@github.com wrote:
> 
> Facebook does a similar thing to what you are suggesting:
> 
>   • Chronological display of the most recent 'x' posts
>   • Option to 'show previous comments'
> —
> Reply to this email directly or view it on GitHub.

## 

Ben Ackland, Projects Director
Netsight Internet Solutions Limited
Tel: +44 (0)117 90 90 90 1

Registered in England no. 3892180
Registered office: 40 Berkeley Square, Bristol, BS8 1HU, United Kingdom

**Comment by mattss** [comment]
@wengole Could you have a go at this? @pysailor may be able to provide some assistance

**Comment by mattss** [comment]
An update here:

Comments are posted in chronological order, and if you post a new comment, pat-inject sticks it at the bottom of the comment listing (as expected).

However if you reload a feed with a comment posted on the current date, it is shown at the top of the comments. Current assumption is that, because todays comments show only the time (with no date), the comment ordering is putting them first. Ordering needs to be done _before_ the date is removed from today's comments. @wengole to investigate solving this.
