### ISSUE TITLE
Remove traces of grok (plone.directives.form)

### ISSUE THREAD

**Issue by pbauer** [ploneintranet/ploneintranet#859]
Grok is still used (e.g. in https://github.com/ploneintranet/ploneintranet/blob/master/src/ploneintranet/todo/behaviors.py). All usages of plone.directives should be replaced by the grok-less best-practice.

**Comment by mattss** [comment]
To clarify, there are no direct uses of grok in the stack, but a number of packages use plone.directives.form, which has grok dependencies.
