### ISSUE TITLE
Search - Work-around for scorched lack of support partial updates

### ISSUE THREAD

**Issue by mgrbyte** [ploneintranet/ploneintranet#881]
@pilz reported to @mattss that solr partial updates seem to be breaking search.

The search implementation [attempts](https://github.com/ploneintranet/ploneintranet/blob/master/src/ploneintranet/search/solr/indexers.py#L150-L156) to utilise partial updates with Solr, but fails to do so.

**Comment by mattss** [comment]
@mgrbyte the PR in #882 breaks things - see http://jenkins.ploneintranet.net/job/complete.Ploneintranet.master.False/520/console

(Integration tests for ploneintranet.workspace get an import error)

**Comment by mgrbyte** [comment]
@mattss Seems to be a jenkins-only issue. I checked out the branch a ran the tests locally without issue.

**Comment by mattss** [comment]
Broken tests were actually caused by #872. Developing a fix now
