### ISSUE TITLE
help needed . This is not an issue

### ISSUE THREAD

**Issue by sudhan77** [ploneintranet/ploneintranet#890]
I have used the installation manual to install venus in a cloud server. however when i go to http://(domain-ip):8080 I dont get anything. I have used plone 4.3 and plone 5. I am aware of all tricks there. the stack used here is little new for  me. please help me if there is any trick.

**Comment by pilz** [comment]
Take a look at parts/instance/zope.cfg to see if your instance is bound to localhost only.
Can you contact it when logged into your server using curl or similar? Or portmap to localhost:8080 and see if it is there. If not, double check that the server is actually running. 

There is nothing different here to a normal Plone. However PI only runs on Plone 5 so I wonder how you would have tried Plone 4.3…

**Comment by sudhan77** [comment]
i have got something wrong. Inside /venus/parts/ there are 2 folders
instance and instance2. both of them have got folders bin, etc, inituser,
var but no zope.cfg

On Sun, Nov 29, 2015 at 5:55 PM, Alexander Pilz notifications@github.com
wrote:

> Take a look at parts/instance/zope.cfg to see if your instance is bound to
> localhost only.
> Can you contact it when logged into your server using curl or similar? Or
> portmap to localhost:8080 and see if it is there. If not, double check that
> the server is actually running.
> 
> There is nothing different here to a normal Plone. However PI only runs on
> Plone 5 so I wonder how you would have tried Plone 4.3…
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ploneintranet/ploneintranet/issues/890#issuecomment-160413328
> .

## 

Sudhanshu

**Comment by sudhan77** [comment]
Can you help me with what the following means

-v $(PWD):/app -w /app -u app $(PROJECT)

taken from

docker run -i -t \
        --net=host \
        -e LC_ALL=en_US.UTF-8 \
        -e LANG=en_US.UTF-8 \
        -v $(PWD):/app -w /app -u app $(PROJECT)

I was earlier stuck trying to use docker and then tried to do the manual
install..there may have been errors because of that

Thanks
Sudhanshu

On Sun, Nov 29, 2015 at 7:47 PM, Sudhanshu Sekhar Pani sudhan77@gmail.com
wrote:

> i have got something wrong. Inside /venus/parts/ there are 2 folders
> instance and instance2. both of them have got folders bin, etc, inituser,
> var but no zope.cfg
> 
> On Sun, Nov 29, 2015 at 5:55 PM, Alexander Pilz notifications@github.com
> wrote:
> 
> > Take a look at parts/instance/zope.cfg to see if your instance is bound
> > to localhost only.
> > Can you contact it when logged into your server using curl or similar? Or
> > portmap to localhost:8080 and see if it is there. If not, double check that
> > the server is actually running.
> > 
> > There is nothing different here to a normal Plone. However PI only runs
> > on Plone 5 so I wonder how you would have tried Plone 4.3…
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ploneintranet/ploneintranet/issues/890#issuecomment-160413328
> > .
> 
> ## 
> 
> Sudhanshu

## 

Sudhanshu

**Comment by pilz** [comment]
Sorry, I am not familiar with the docker parts.

It would though be helpful if you first get a bit familiar with the setup by installing it locally. Does it work for you there? You should follow the steps in the b) Manual section at http://docs.ploneintranet.org/installation/quickstart.html. That works for me.

Look for error messages on the way. Likely you were missing some dependencies and the buildout process stopped.

**Comment by pilz** [comment]
This hopefully works now?
