### ISSUE TITLE
Kick jenkins into submission

### ISSUE THREAD

**Issue by pbauer** [ploneintranet/ploneintranet#896]
Can someone please kick jenkins? There is a job that seem to hang since 27. November (https://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/1042/). I created a PR to upgrade to Plone 5.0.2 that I'd like to test...

**Comment by ckirchhoff** [comment]
stopped it!

2016-01-18 16:36 GMT+01:00 Philip Bauer notifications@github.com:
