### ISSUE TITLE
Instance fails to start with python 2.7.11 should be fixed by upgrading komba

### ISSUE THREAD

**Issue by cillianderoiste** [ploneintranet/ploneintranet#897]
@angeldasangel ran into an issue with a project that uses PI, and I assume it will also be a problem for vanilla PI. The instance fails to start with the following error:

```
ZopeXMLConfigurationError: File "/Users/steinhardt/dev/ikath.deployment/work/zope/src/ploneintranet/src/ploneintranet/configure.zcml", line 2.4-2.31
    ZopeXMLConfigurationError: File "/Users/steinhardt/dev/ikath.deployment/work/zope/src/ploneintranet/src/ploneintranet/suite/configure.zcml", line 14.2-14.42
    ZopeXMLConfigurationError: File "/Users/steinhardt/dev/ikath.deployment/work/zope/src/ploneintranet/src/ploneintranet/async/configure.zcml", line 10.2-10.32
    ZopeXMLConfigurationError: File "/Users/steinhardt/dev/ikath.deployment/work/zope/src/ploneintranet/src/ploneintranet/async/browser/configure.zcml", line 11.2-18.8
    ImportError: cannot import name _uuid_generate_random
```

Here's another reference: 
    http://stackoverflow.com/questions/34198538/cannot-import-name-uuid-generate-random-in-heroku-django

Here's the upstream issue:
    https://github.com/celery/kombu/issues/545

Downgrading python to 2.7.10 is a way to work around the issue.

Upgrading kombu (required by celery) 3.0.30 should fix it.

**Comment by pilz** [comment]
upgraded.
