### ISSUE TITLE
less-file in src/less

### ISSUE THREAD

**Issue by pbauer** [ploneintranet/ploneintranet#96]
The file `/src/less/pattern.upload.less` is in a weird location. Should be moved to theme.

**Comment by gyst** [comment]
@jcbrand any specific reason you put the file there, or just fallout of the package consolidation?

**Comment by jcbrand** [comment]
I actually don't think that file is needed (it comes from Mockup's upload pattern), and yes it's not really consciously there.

Should be fine to just remove it.
