### ISSUE TITLE
Move prototype to a separate git repo

### ISSUE THREAD

**Issue by mattss** [ploneintranet/ploneintranet#98]
Merging the theme egg in with the rest of the codebase has introduced a lot of noise in github, largely because the _prototype_ and the codebase are managed very differently. Additionally, the makefile situation is quite messy - see https://github.com/ploneintranet/ploneintranet/issues/95

After discussion with @adrianwhite, we propose to keep the ploneintranet.theme diazo package with everything else, but move the actual prototype back out again. This will allow us to keep implementation of the UI separate to its development. 

We would then have an automated 'sync' action that copies the relevant resources from the prototype into the theme part of ploneintranet. This can be actioned manually by an integrator as and when new features from the prototype are to be implemented. This is especially important because the design-first approach means the prototype will always be _ahead_ of the backend. When @cornae begins to adapt things for Venus and other future releases, we don't want those changes to affect the Mercury codebase.

This would also mean that developers would not need the entire jekyll/npm stack in order to contribute to plone intranet.

We have been running this workflow on a client project and it has proved invaluable for this kind of theme development.

**Comment by jcbrand** [comment]
+1

We can check out the proto via mr.developer and we already have `make diazo` which basically does what you mean with "automated sync".

**Comment by gyst** [comment]
+1 but I'd like to hear from @pilz as well.

**Comment by pilz** [comment]
Fine with me. My main argument for the unification of packages was to allow developers to do one branch, one pull request, one action to test something. The prototype is nearly disjunctive in terms of staff, so these arguments don't apply too much. Even more, it might even address one of @gyst 's wishes to keep the theme alone for better customisability (don't know if it helps, but it does certainly not hurt) so +1

**Comment by jcbrand** [comment]
This will require coordination with @cornae, since he'll have to change to a new remote repo for the proto.

**Comment by cornae** [comment]
No problem with a having proto in separate repo. @mattss , regardless of that, I don't think Venus would necessarily have to disturb anything if it would be another branch of the same repo. I think any developer needs the Jekyll prototype though since its HTML and HTML/Liquid pages are the markup spec and sometimes also contain details about the business logic.

**Comment by mattss** [comment]
Is this resolved by #145 ?

**Comment by pilz** [comment]
+1

**Comment by jcbrand** [comment]
Yes. I'll close.
